export const SHIPING_GET_QUOTES = 'SHIPING_GET_QUOTES'
export const SHIPING_GET_QUOTES_PENDING = 'SHIPING_GET_QUOTES_PENDING'
export const SHIPING_GET_QUOTES_REJECTED = 'SHIPING_GET_QUOTES_REJECTED'
export const SHIPING_GET_QUOTES_FULFILLED = 'SHIPING_GET_QUOTES_FULFILLED'

export const SHIPING_FORM_INIT = 'SHIPING_FORM_INIT'
export const SHIPING_FORM_INIT_FULFILLED = 'SHIPING_FORM_INIT_FULFILLED'
export const SHIPING_FORM_INIT_REJECTED = 'SHIPING_FORM_INIT_REJECTED'
export const SHIPING_FORM_INIT_PENDING = 'SHIPING_FORM_INIT_PENDING'

export const SHIPPING_CLEAR_QUOTES = 'SHIPPING_CLEAR_QUOTES'
