export const SHIPPING_GET_QUOTES = 'SHIPPING_GET_QUOTES'
export const SHIPPING_GET_QUOTES_PENDING = 'SHIPPING_GET_QUOTES_PENDING'
export const SHIPPING_GET_QUOTES_REJECTED = 'SHIPPING_GET_QUOTES_REJECTED'
export const SHIPPING_GET_QUOTES_FULFILLED = 'SHIPPING_GET_QUOTES_FULFILLED'