export const SHIPPING_GET_QUOTES = 'SHIPPING_GET_QUOTES'
export const SHIPPING_GET_QUOTES_PENDING = 'SHIPPING_GET_QUOTES_PENDING'
export const SHIPPING_GET_QUOTES_REJECTED = 'SHIPPING_GET_QUOTES_REJECTED'
export const SHIPPING_GET_QUOTES_FULFILLED = 'SHIPPING_GET_QUOTES_FULFILLED'

export const SHIPPING_FORM_INIT = 'SHIPPING_FORM_INIT'
export const SHIPPING_FORM_INIT_FULFILLED = 'SHIPPING_FORM_INIT_FULFILLED'
export const SHIPPING_FORM_INIT_REJECTED = 'SHIPPING_FORM_INIT_REJECTED'
export const SHIPPING_FORM_INIT_PENDING = 'SHIPPING_FORM_INIT_PENDING'

export const SHIPPING_CLEAR_QUOTES = 'SHIPPING_CLEAR_QUOTES'

export const SHIPPING_GET_ZIP_CODES = 'SHIPPING_GET_ZIP_CODES'
export const SHIPPING_GET_ZIP_CODES_FULFILLED = 'SHIPPING_GET_ZIP_CODES_FULFILLED'
export const SHIPPING_GET_ZIP_CODES_REJECTED = 'SHIPPING_GET_ZIP_CODES_REJECTED'
export const SHIPPING_GET_ZIP_CODES_PENDING = 'SHIPPING_GET_ZIP_CODES_PENDING'

export const SHIPPING_GET_COUNTRIES = 'SHIPPING_GET_COUNTRIES'
export const SHIPPING_GET_COUNTRIES_FULFILLED = 'SHIPPING_GET_COUNTRIES_FULFILLED'
export const SHIPPING_GET_COUNTRIES_REJECTED = 'SHIPPING_GET_COUNTRIES_REJECTED'
export const SHIPPING_GET_COUNTRIES_PENDING = 'SHIPPING_GET_COUNTRIES_PENDING'