export const NEXT_STEP = 'NEXT_STEP'
export const PREV_STEP = 'PREV_STEP'
export const CLEARE_ACTIVE_STEP = 'CLEARE_ACTIVE_STEP'
export const COUNT_BENEFICIAL_OWNERS = 'COUNT_BENEFICIAL_OWNERS'

export const VELLOCI_REG_OPEN_EMAIL_POPUP = 'VELLOCI_REG_OPEN_EMAIL_POPUP'
export const VELLOCI_REG_CLOSE_EMAIL_POPUP = 'VELLOCI_REG_CLOSE_EMAIL_POPUP'

export const REGISTER_VELLOCI = 'REGISTER_VELLOCI'
export const REGISTER_VELLOCI_PENDING = 'REGISTER_VELLOCI_PENDING'
export const REGISTER_VELLOCI_REJECTED = 'REGISTER_VELLOCI_REJECTED'
export const REGISTER_VELLOCI_FULFILLED = 'REGISTER_VELLOCI_FULFILLED'

export const UPLOAD_DOCUMENTS = 'UPLOAD_DOCUMENTS'
export const UPLOAD_DOCUMENTS_PENDING = 'UPLOAD_DOCUMENTS_PENDING'
export const UPLOAD_DOCUMENTS_REJECTED = 'UPLOAD_DOCUMENTS_REJECTED'
export const UPLOAD_DOCUMENTS_FULFILLED = 'UPLOAD_DOCUMENTS_FULFILLED'

export const GET_BUSINESS_TYPES = 'GET_BUSINESS_TYPES'
export const GET_BUSINESS_TYPES_PENDING = 'GET_BUSINESS_TYPES_PENDING'
export const GET_BUSINESS_TYPES_REJECTED = 'GET_BUSINESS_TYPES_REJECTED'
export const GET_BUSINESS_TYPES_FULFILLED = 'GET_BUSINESS_TYPES_FULFILLED'

export const GET_NAICS_CODES = 'GET_NAICS_CODES'
export const GET_NAICS_CODES_PENDING = 'GET_NAICS_CODES_PENDING'
export const GET_NAICS_CODES_REJECTED = 'GET_NAICS_CODES_REJECTED'
export const GET_NAICS_CODES_FULFILLED = 'GET_NAICS_CODES_FULFILLED'

export const GET_VELLOCI_BUSINESS_ROLES = 'GET_VELLOCI_BUSINESS_ROLES'
export const GET_VELLOCI_BUSINESS_ROLES_PENDING = 'GET_VELLOCI_BUSINESS_ROLES_PENDING'
export const GET_VELLOCI_BUSINESS_ROLES_REJECTED = 'GET_VELLOCI_BUSINESS_ROLES_REJECTED'
export const GET_VELLOCI_BUSINESS_ROLES_FULFILLED = 'GET_VELLOCI_BUSINESS_ROLES_FULFILLED'

export const GET_VELLOCI_ENTITY_DOCUMENTS = 'GET_VELLOCI_ENTITY_DOCUMENTS'
export const GET_VELLOCI_ENTITY_DOCUMENTS_PENDING = 'GET_VELLOCI_ENTITY_DOCUMENTS_PENDING'
export const GET_VELLOCI_ENTITY_DOCUMENTS_REJECTED = 'GET_VELLOCI_ENTITY_DOCUMENTS_REJECTED'
export const GET_VELLOCI_ENTITY_DOCUMENTS_FULFILLED = 'GET_VELLOCI_ENTITY_DOCUMENTS_FULFILLED'

export const GET_VELLOCI_POLITICALLY_EXPOSED_PERSONS = 'GET_VELLOCI_POLITICALLY_EXPOSED_PERSONS'
export const GET_VELLOCI_POLITICALLY_EXPOSED_PERSONS_PENDING = 'GET_VELLOCI_POLITICALLY_EXPOSED_PERSONS_PENDING'
export const GET_VELLOCI_POLITICALLY_EXPOSED_PERSONS_REJECTED = 'GET_VELLOCI_POLITICALLY_EXPOSED_PERSONS_REJECTED'
export const GET_VELLOCI_POLITICALLY_EXPOSED_PERSONS_FULFILLED = 'GET_VELLOCI_POLITICALLY_EXPOSED_PERSONS_FULFILLED'

export const GET_VELLOCI_TIN_TYPES = 'GET_VELLOCI_TIN_TYPES'
export const GET_VELLOCI_TIN_TYPES_PENDING = 'GET_VELLOCI_TIN_TYPES_PENDING'
export const GET_VELLOCI_TIN_TYPES_REJECTED = 'GET_VELLOCI_TIN_TYPES_REJECTED'
export const GET_VELLOCI_TIN_TYPES_FULFILLED = 'GET_VELLOCI_TIN_TYPES_FULFILLED'

export const GET_VELLOCI_BUSINESS_DETAILS = 'GET_VELLOCI_BUSINESS_DETAILS'
export const GET_VELLOCI_BUSINESS_DETAILS_PENDING = 'GET_VELLOCI_BUSINESS_DETAILS_PENDING'
export const GET_VELLOCI_BUSINESS_DETAILS_REJECTED = 'GET_VELLOCI_BUSINESS_DETAILS_REJECTED'
export const GET_VELLOCI_BUSINESS_DETAILS_FULFILLED = 'GET_VELLOCI_BUSINESS_DETAILS_FULFILLED'

export const GET_VELLOCI_BUSINESS_MARKETS = 'GET_VELLOCI_BUSINESS_MARKETS'
export const GET_VELLOCI_BUSINESS_MARKETS_PENDING = 'GET_VELLOCI_BUSINESS_MARKETS_PENDING'
export const GET_VELLOCI_BUSINESS_MARKETS_REJECTED = 'GET_VELLOCI_BUSINESS_MARKETS_REJECTED'
export const GET_VELLOCI_BUSINESS_MARKETS_FULFILLED = 'GET_VELLOCI_BUSINESS_MARKETS_FULFILLED'

export const GET_VELLOCI_BUSINESS_TYPES = 'GET_VELLOCI_BUSINESS_TYPES'
export const GET_VELLOCI_BUSINESS_TYPES_PENDING = 'GET_VELLOCI_BUSINESS_TYPES_PENDING'
export const GET_VELLOCI_BUSINESS_TYPES_REJECTED = 'GET_VELLOCI_BUSINESS_TYPES_REJECTED'
export const GET_VELLOCI_BUSINESS_TYPES_FULFILLED = 'GET_VELLOCI_BUSINESS_TYPES_FULFILLED'

export const VELLOCI_ON_EVENT = 'VELLOCI_ON_EVENT'

export const VELLOCI_GET_TOKEN = 'VELLOCI_GET_TOKEN'

export const VELLOCI_ADD_ACOUNT = 'VELLOCI_ADD_ACOUNT'

export const LOAD_SUBMIT_BUTTON = 'LOAD_SUBMIT_BUTTON'

export const VELLOCI_INVITE_BENEFICIAL_OWNERS = 'VELLOCI_INVITE_BENEFICIAL_OWNERS'
export const VELLOCI_INVITE_BENEFICIAL_OWNERS_PENDING = 'VELLOCI_INVITE_BENEFICIAL_OWNERS_PENDING'
export const VELLOCI_INVITE_BENEFICIAL_OWNERS_REJECTED = 'VELLOCI_INVITE_BENEFICIAL_OWNERS_REJECTED'
export const VELLOCI_INVITE_BENEFICIAL_OWNERS_FULFILLED = 'VELLOCI_INVITE_BENEFICIAL_OWNERS_FULFILLED'
export const VELLOCI_SET_NOTIFIED_OWNERS = 'VELLOCI_SET_NOTIFIED_OWNERS'

export const VELLOCI_REGISTER_BENEFICIAL_OWNERS = 'VELLOCI_REGISTER_BENEFICIAL_OWNERS'
export const VELLOCI_REGISTER_BENEFICIAL_OWNERS_PENDING = 'VELLOCI_REGISTER_BENEFICIAL_OWNERS_PENDING'
export const VELLOCI_REGISTER_BENEFICIAL_OWNERS_REJECTED = 'VELLOCI_REGISTER_BENEFICIAL_OWNERS_REJECTED'
export const VELLOCI_REGISTER_BENEFICIAL_OWNERS_FULFILLED = 'VELLOCI_REGISTER_BENEFICIAL_OWNERS_FULFILLED'

export const VELLOCI_CHECK_MAGIC_TOKEN = 'VELLOCI_CHECK_MAGIC_TOKEN'
export const VELLOCI_CHECK_MAGIC_TOKEN_PENDING = 'VELLOCI_CHECK_MAGIC_TOKEN_PENDING'
export const VELLOCI_CHECK_MAGIC_TOKEN_REJECTED = 'VELLOCI_CHECK_MAGIC_TOKEN_REJECTED'
export const VELLOCI_CHECK_MAGIC_TOKEN_FULFILLED = 'VELLOCI_CHECK_MAGIC_TOKEN_FULFILLED'

export const VELLOCI_APPLICATION_SUBMITTED = 'VELLOCI_APPLICATION_SUBMITTED'

export const VELLOCI_COI_DOCUMENT_UPLOADED = 'VELLOCI_COI_DOCUMENT_UPLOADED'
