export const NEXT_STEP = 'NEXT_STEP'
export const PREV_STEP = 'PREV_STEP'
export const CLEARE_ACTIVE_STEP = 'CLEARE_ACTIVE_STEP'
export const COUNT_BENEFICIAL_OWNERS = 'COUNT_BENEFICIAL_OWNERS'

export const REGISTER_VELLOCI = 'REGISTER_VELLOCI'
export const REGISTER_VELLOCI_PENDING = 'REGISTER_VELLOCI_PENDING'
export const REGISTER_VELLOCI_REJECTED = 'REGISTER_VELLOCI_REJECTED'
export const REGISTER_VELLOCI_FULFILLED = 'REGISTER_VELLOCI_FULFILLED'

export const GET_ENTITY_TYPES = 'GET_ENTITY_TYPES'
export const GET_ENTITY_TYPES_PENDING = 'GET_ENTITY_TYPES_PENDING'
export const GET_ENTITY_TYPES_REJECTED = 'GET_ENTITY_TYPES_REJECTED'
export const GET_ENTITY_TYPES_FULFILLED = 'GET_ENTITY_TYPES_FULFILLED'

export const GET_NAICS_CODES = 'GET_NAICS_CODES'
export const GET_NAICS_CODES_PENDING = 'GET_NAICS_CODES_PENDING'
export const GET_NAICS_CODES_REJECTED = 'GET_NAICS_CODES_REJECTED'
export const GET_NAICS_CODES_FULFILLED = 'GET_NAICS_CODES_FULFILLED'
