export const GET_DASHBOARD_DATA = 'GET_DASHBOARD_DATA'
export const GET_DASHBOARD_DATA_FULFILLED = 'GET_DASHBOARD_DATA_FULFILLED'
export const GET_DASHBOARD_DATA_REJECTED = 'GET_DASHBOARD_DATA_REJECTED'
export const GET_DASHBOARD_DATA_PENDING = 'GET_DASHBOARD_DATA_PENDING'
