export const GET_DASHBOARD_DATA = 'GET_DASHBOARD_DATA'
export const GET_DASHBOARD_DATA_FULFILLED = 'GET_DASHBOARD_DATA_FULFILLED'
export const GET_DASHBOARD_DATA_REJECTED = 'GET_DASHBOARD_DATA_REJECTED'
export const GET_DASHBOARD_DATA_PENDING = 'GET_DASHBOARD_DATA_PENDING'

export const GET_DAILY_STATISTICS = 'GET_DAILY_STATISTICS'
export const GET_DAILY_STATISTICS_PENDING = 'GET_DAILY_STATISTICS_PENDING'
export const GET_DAILY_STATISTICS_FULFILLED = 'GET_DAILY_STATISTICS_FULFILLED'
export const GET_DAILY_STATISTICS_REJECTED = 'GET_DAILY_STATISTICS_REJECTED'
