export const OPEN_POPUP = "OPEN_POPUP"
export const CLOSE_POPUP = "CLOSE_POPUP"

export const OPEN_DWOLLA_POPUP = "OPEN_DWOLLA_POPUP"
export const CLOSE_DWOLLA_POPUP = "CLOSE_DWOLLA_POPUP"

export const OPEN_IMPORT_POPUP = "OPEN_IMPORT_POPUP"
export const SETTINGS_CLOSE_IMPORT_POPUP = "SETTINGS_CLOSE_IMPORT_POPUP"
export const SETTINGS_CLOSE_IMPORT_POPUP_FULFILLED = "SETTINGS_CLOSE_IMPORT_POPUP_FULFILLED"
export const CLOSE_IMPORT_POPUP_CANCEL = "CLOSE_IMPORT_POPUP_CANCEL"

export const OPEN_EDIT_POPUP = "OPEN_EDIT_POPUP"
export const CLOSE_EDIT_POPUP = "CLOSE_EDIT_POPUP"
export const OPEN_ADD_POPUP = "OPEN_ADD_POPUP"
export const CLOSE_ADD_POPUP = "CLOSE_ADD_POPUP"
export const OPEN_CONFIRM_POPUP = "OPEN_CONFIRM_POPUP"
export const CLOSE_CONFIRM_POPUP = "CLOSE_CONFIRM_POPUP"
export const DELETE_CONFIRM_POPUP = "DELETE_CONFIRM_POPUP"
export const OPEN_ROLES_POPUP = "OPEN_ROLES_POPUP"
export const CLOSE_ROLES_POPUP = "CLOSE_ROLES_POPUP"
export const CONFIRM_FULFILLED = "CONFIRM_FULFILLED"
export const OPEN_TOAST = "OPEN_TOAST"
export const CLOSE_TOAST = "CLOSE_TOAST"

export const SUBMIT_EDIT_POPUP_HANDLER = "SUBMIT_EDIT_POPUP_HANDLER"
//export const HANDLE_ACTIVE_TAB = "HANDLE_ACTIVE_TAB"
export const HANDLE_FILTERS_VALUE = "HANDLE_FILTERS_VALUE"
export const HANDLE_PRODUCT_CATALOG_UNMAPPED_VALUE = "HANDLE_PRODUCT_CATALOG_UNMAPPED_VALUE"
export const HANDLE_SUBMIT_USER_EDIT_POPUP = "HANDLE_SUBMIT_USER_EDIT_POPUP"
export const CHANGE_HEADERS_CSV = "CHANGE_HEADERS_CSV"
export const DATA_HEADER_CSV = "DATA_HEADER_CSV"
export const SETTINGS_CLEAR_DATA_OF_CSV = "SETTINGS_CLEAR_DATA_OF_CSV"

export const GET_USERS_DATA = "GET_USERS_DATA"
export const GET_ROLES_DATA = "GET_ROLES_DATA"
export const GET_USERS_DATA_FULFILLED = "GET_USERS_DATA_FULFILLED"
export const GET_WAREHOUSES_DATA = "GET_WAREHOUSES_DATA"
export const GET_WAREHOUSES_DATA_FULFILLED = "GET_WAREHOUSES_DATA_FULFILLED"
export const GET_BRANCHES_DATA = "GET_BRANCHES_DATA"
export const GET_ALL_BRANCHES_DATA = "GET_ALL_BRANCHES_DATA"
export const GET_BRANCHES_DATA_FULFILLED = "GET_BRANCHES_DATA_FULFILLED"
export const GET_CREDIT_CARDS_DATA = "GET_CREDIT_CARDS_DATA"
export const GET_CREDIT_CARDS_DATA_FULFILLED = "GET_CREDIT_CARDS_DATA_FULFILLED"
export const GET_BANK_ACCOUNTS_DATA = "GET_BANK_ACCOUNTS_DATA"
export const GET_BANK_ACCOUNTS_DATA_FULFILLED = "GET_BANK_ACCOUNTS_DATA_FULFILLED"
export const GET_PRODUCTS_WITH_REQUIRED_PARAM =
  "GET_PRODUCTS_WITH_REQUIRED_PARAM"
export const GET_PRODUCTS_WITH_REQUIRED_PARAM_FULFILLED =
  "GET_PRODUCTS_WITH_REQUIRED_PARAM_FULFILLED"
export const SETTINGS_GET_STORED_CSV = "SETTINGS_GET_STORED_CSV"
export const SETTINGS_GET_STORED_CSV_FULFILLED = "SETTINGS_GET_STORED_CSV_FULFILLED"
export const PUT_NEW_USER_ROLES_REQUEST = "PUT_NEW_USER_ROLES_REQUEST"
export const PUT_WAREHOUSE_EDIT_POPUP = "PUT_WAREHOUSE_EDIT_POPUP"
export const PUT_BRANCHES_EDIT_POPUP = "PUT_BRANCHES_POPUP"
//export const PUT_PRODUCT_EDIT_POPUP = "PUT_PRODUCT_EDIT_POPUP"
export const PUT_BANK_ACCOUNT_EDIT_POPUP = "PUT_BANK_ACCOUNT_EDIT_POPUP"

export const POST_NEW_USER_REQUEST = "POST_NEW_USER_REQUEST"
export const POST_NEW_WAREHOUSE_POPUP = "POST_NEW_WAREHOUSE_POPUP"
export const POST_NEW_WAREHOUSE_REQUEST = "POST_NEW_WAREHOUSE_REQUEST"
export const POST_NEW_BRANCHES_REQUEST = "POST_NEW_BRANCHES_REQUEST"
export const POST_NEW_CREDIT_CARD_REQUEST = "POST_NEW_CREDIT_CARD_REQUEST"
export const POST_NEW_BANK_ACCOUNT_REQUEST = "POST_NEW_BANK_ACCOUNT_REQUEST"
//export const POST_NEW_PRODUCT_REQUEST = "POST_NEW_PRODUCT_REQUEST"  // ! ! delete
export const POST_UPLOAD_CSV_FILE = "POST_UPLOAD_CSV_FILE"
export const POST_UPLOAD_CSV_FILE_FULFILLED = "POST_UPLOAD_CSV_FILE_FULFILLED"

export const SETTINGS_POST_CSV_IMPORT_PRODUCTS = "SETTINGS_POST_CSV_IMPORT_PRODUCTS"
export const SETTINGS_POST_CSV_IMPORT_PRODUCTS_FULFILLED =
  "SETTINGS_POST_CSV_IMPORT_PRODUCTS_FULFILLED"

export const SEARCH_CAS_PRODUCT = "SEARCH_CAS_PRODUCT"
export const SEARCH_CAS_PRODUCT_FULFILLED = "SEARCH_CAS_PRODUCT_FULFILLED"

export const SEARCH_UN_NUMBER = "SEARCH_UN_NUMBER"
export const SEARCH_UN_NUMBER_FULFILLED = "SEARCH_UN_NUMBER_FULFILLED"

export const DELETE_USER = "DELETE_USER"
export const DELETE_WAREHOUSE = "DELETE_WAREHOUSE"
export const DELETE_CREDIT_CARD = "DELETE_CREDIT_CARD"
export const DELETE_BANK_ACCOUNT = "DELETE_BANK_ACCOUNT"

export const SETTINGS_GET_DELIVERY_ADDRESSES_BY_STRING = "SETTINGS_GET_DELIVERY_ADDRESSES_BY_STRING"
export const SETTINGS_GET_DELIVERY_ADDRESSES_BY_STRING_PENDING = "SETTINGS_GET_DELIVERY_ADDRESSES_BY_STRING_PENDING"
export const SETTINGS_GET_DELIVERY_ADDRESSES_BY_STRING_FULFILLED = "SETTINGS_GET_DELIVERY_ADDRESSES_BY_STRING_FULFILLED"
export const SETTINGS_GET_DELIVERY_ADDRESSES_BY_STRING_REJECTED = "SETTINGS_GET_DELIVERY_ADDRESSES_BY_STRING_REJECTED"

export const SETTINGS_GET_DELIVERY_ADDRESSES_BY_FILTER = "SETTINGS_GET_DELIVERY_ADDRESSES_BY_FILTER"
export const SETTINGS_GET_DELIVERY_ADDRESSES_BY_FILTER_PENDING = "SETTINGS_GET_DELIVERY_ADDRESSES_BY_FILTER_PENDING"
export const SETTINGS_GET_DELIVERY_ADDRESSES_BY_FILTER_FULFILLED = "SETTINGS_GET_DELIVERY_ADDRESSES_BY_FILTER_FULFILLED"
export const SETTINGS_GET_DELIVERY_ADDRESSES_BY_FILTER_REJECTED = "SETTINGS_GET_DELIVERY_ADDRESSES_BY_FILTER_REJECTED"

export const SETTINGS_DELETE_DELIVERY_ADDRESSES = "SETTINGS_DELETE_DELIVERY_ADDRESSES"
export const SETTINGS_DELETE_DELIVERY_ADDRESSES_PENDING = "SETTINGS_DELETE_DELIVERY_ADDRESSES_PENDINGSETTINGS_DELETE_DELIVERY_ADDRESSES_PENDING"
export const SETTINGS_DELETE_DELIVERY_ADDRESSES_FULFILLED = "SETTINGS_DELETE_DELIVERY_ADDRESSES_FULFILLED"
export const SETTINGS_DELETE_DELIVERY_ADDRESSES_REJECTED = "SETTINGS_DELETE_DELIVERY_ADDRESSES_REJECTED"

export const SETTINGS_GET_COUNTRIES = 'SETTINGS_GET_COUNTRIES'
export const SETTINGS_GET_COUNTRIES_PENDING = 'SETTINGS_GET_COUNTRIES_PENDING'
export const SETTINGS_GET_COUNTRIES_FULFILLED = 'SETTINGS_GET_COUNTRIES_FULFILLED'
export const SETTINGS_GET_COUNTRIES_REJECTED = 'SETTINGS_GET_COUNTRIES_REJECTED'

export const SETTINGS_GET_PROVINCES = 'SETTINGS_GET_PROVINCES'
export const SETTINGS_GET_PROVINCES_PENDING = 'SETTINGS_GET_PROVINCES_PENDING'
export const SETTINGS_GET_PROVINCES_FULFILLED = 'SETTINGS_GET_PROVINCES_FULFILLED'
export const SETTINGS_GET_PROVINCES_REJECTED = 'SETTINGS_GET_PROVINCES_REJECTED'

export const SETTINGS_UPDATE_DELIVERY_ADDRESSES = "SETTINGS_UPDATE_DELIVERY_ADDRESSES"
export const SETTINGS_UPDATE_DELIVERY_ADDRESSES_PENDING = "SETTINGS_UPDATE_DELIVERY_ADDRESSES_PENDING"
export const SETTINGS_UPDATE_DELIVERY_ADDRESSES_FULFILLED = "SETTINGS_UPDATE_DELIVERY_ADDRESSES_FULFILLED"
export const SETTINGS_UPDATE_DELIVERY_ADDRESSES_REJECTED = "SETTINGS_UPDATE_DELIVERY_ADDRESSES_REJECTED"

export const SETTINGS_CREATE_NEW_DELIVERY_ADDRESS = "SETTINGS_CREATE_NEW_DELIVERY_ADDRESS"
export const SETTINGS_CREATE_NEW_DELIVERY_ADDRESS_PENDING = "SETTINGS_CREATE_NEW_DELIVERY_ADDRESS_PENDING"
export const SETTINGS_CREATE_NEW_DELIVERY_ADDRESS_FULFILLED = "SETTINGS_CREATE_NEW_DELIVERY_ADDRESS_FULFILLED"
export const SETTINGS_CREATE_NEW_DELIVERY_ADDRESS_REJECTED = "SETTINGS_CREATE_NEW_DELIVERY_ADDRESS_REJECTED"

export const SETTINGS_GET_PRODUCTS_CATALOG_DATA = "SETTINGS_GET_PRODUCTS_CATALOG_DATA"
export const SETTINGS_GET_PRODUCTS_CATALOG_DATA_PENDING = "SETTINGS_GET_PRODUCTS_CATALOG_DATA_PENDING"
export const SETTINGS_GET_PRODUCTS_CATALOG_DATA_FULFILLED = "SETTINGS_GET_PRODUCTS_CATALOG_DATA_FULFILLED"
export const SETTINGS_GET_PRODUCTS_CATALOG_DATA_REJECTED = "SETTINGS_GET_PRODUCTS_CATALOG_DATA_REJECTED"

export const SETTINGS_POST_NEW_PRODUCT_REQUEST = "SETTINGS_POST_NEW_PRODUCT_REQUEST"
export const SETTINGS_POST_NEW_PRODUCT_REQUEST_PENDING = "SETTINGS_POST_NEW_PRODUCT_REQUEST_PENDING"
export const SETTINGS_POST_NEW_PRODUCT_REQUEST_FULFILLED = "SETTINGS_POST_NEW_PRODUCT_REQUEST_FULFILLED"
export const SETTINGS_POST_NEW_PRODUCT_REQUEST_REJECTED = "SETTINGS_POST_NEW_PRODUCT_REQUEST_REJECTED"

export const SETTINGS_CREATE_PRODUCT_CATALOG = "SETTINGS_CREATE_PRODUCT_CATALOG"
export const SETTINGS_CREATE_PRODUCT_CATALOG_PENDING = "SETTINGS_CREATE_PRODUCT_CATALOG_PENDING"
export const SETTINGS_CREATE_PRODUCT_CATALOG_FULFILLED = "SETTINGS_CREATE_PRODUCT_CATALOG_FULFILLED"
export const SETTINGS_CREATE_PRODUCT_CATALOG_REJECTED = "SETTINGS_CREATE_PRODUCT_CATALOG_REJECTED"

export const SETTINGS_UPDATE_PRODUCT_CATALOG = "SETTINGS_UPDATE_PRODUCT_CATALOG"
export const SETTINGS_UPDATE_PRODUCT_CATALOG_PENDING = "SETTINGS_UPDATE_PRODUCT_CATALOG_PENDING"
export const SETTINGS_UPDATE_PRODUCT_CATALOG_FULFILLED = "SETTINGS_UPDATE_PRODUCT_CATALOG_FULFILLED"
export const SETTINGS_UPDATE_PRODUCT_CATALOG_REJECTED = "SETTINGS_UPDATE_PRODUCT_CATALOG_REJECTED"

export const SETTINGS_CREATE_DWOLLA_ACCOUNT = "SETTINGS_CREATE_DWOLLA_ACCOUNT"
export const SETTINGS_CREATE_DWOLLA_ACCOUNT_PENDING = "SETTINGS_CREATE_DWOLLA_ACCOUNT_PENDING"
export const SETTINGS_CREATE_DWOLLA_ACCOUNT_FULFILLED = "SETTINGS_CREATE_DWOLLA_ACCOUNT_FULFILLED"
export const SETTINGS_CREATE_DWOLLA_ACCOUNT_REJECTED = "SETTINGS_CREATE_DWOLLA_ACCOUNT_REJECTED"

export const ADD_TAB = 'ADD_TAB'

