export const OPEN_POPUP = 'OPEN_POPUP'
export const OPEN_POPUP2 = 'OPEN_POPUP2'
export const CLOSE_POPUP = 'CLOSE_POPUP'

export const OPEN_DWOLLA_POPUP = 'OPEN_DWOLLA_POPUP'
export const CLOSE_DWOLLA_POPUP = 'CLOSE_DWOLLA_POPUP'

export const OPEN_IMPORT_POPUP = 'OPEN_IMPORT_POPUP'
export const SETTINGS_CLOSE_IMPORT_POPUP = 'SETTINGS_CLOSE_IMPORT_POPUP'
export const SETTINGS_CLOSE_IMPORT_POPUP_FULFILLED = 'SETTINGS_CLOSE_IMPORT_POPUP_FULFILLED'

export const SETTINGS_OPEN_UPLOAD_DOCUMENTS_POPUP = 'SETTINGS_OPEN_UPLOAD_DOCUMENTS_POPUP'
export const SETTINGS_CLOSE_UPLOAD_DOCUMENTS_POPUP = 'SETTINGS_CLOSE_UPLOAD_DOCUMENTS_POPUP'
export const SETTINGS_CLOSE_UPLOAD_DOCUMENTS_POPUP_FULFILLED = 'SETTINGS_CLOSE_UPLOAD_DOCUMENTS_POPUP_FULFILLED'
export const SETTINGS_CLOSE_UPLOAD_DOCUMENTS_POPUP_CANCEL = 'SETTINGS_CLOSE_UPLOAD_DOCUMENTS_POPUP_CANCEL'

export const OPEN_EDIT_POPUP = 'OPEN_EDIT_POPUP'
export const CLOSE_EDIT_POPUP = 'CLOSE_EDIT_POPUP'
export const OPEN_ADD_POPUP = 'OPEN_ADD_POPUP'
export const CLOSE_ADD_POPUP = 'CLOSE_ADD_POPUP'
export const OPEN_CONFIRM_POPUP = 'OPEN_CONFIRM_POPUP'
export const CLOSE_CONFIRM_POPUP = 'CLOSE_CONFIRM_POPUP'
export const DELETE_CONFIRM_POPUP = 'DELETE_CONFIRM_POPUP'
export const OPEN_ROLES_POPUP = 'OPEN_ROLES_POPUP'
export const CLOSE_ROLES_POPUP = 'CLOSE_ROLES_POPUP'
export const CONFIRM_FULFILLED = 'CONFIRM_FULFILLED'
export const OPEN_TOAST = 'OPEN_TOAST'
export const CLOSE_TOAST = 'CLOSE_TOAST'

export const SUBMIT_EDIT_POPUP_HANDLER = 'SUBMIT_EDIT_POPUP_HANDLER'
//export const HANDLE_ACTIVE_TAB = 'HANDLE_ACTIVE_TAB'
export const HANDLE_FILTERS_VALUE = 'HANDLE_FILTERS_VALUE'
export const HANDLE_PRODUCT_CATALOG_UNMAPPED_VALUE = 'HANDLE_PRODUCT_CATALOG_UNMAPPED_VALUE'
export const HANDLE_SUBMIT_USER_EDIT_POPUP = 'HANDLE_SUBMIT_USER_EDIT_POPUP'
export const HANDLE_SUBMIT_USER_EDIT_POPUP_FULFILLED = 'HANDLE_SUBMIT_USER_EDIT_POPUP_FULFILLED'
export const CHANGE_HEADERS_CSV = 'CHANGE_HEADERS_CSV'
export const DATA_HEADER_CSV = 'DATA_HEADER_CSV'
export const SETTINGS_CLEAR_DATA_OF_CSV = 'SETTINGS_CLEAR_DATA_OF_CSV'

export const GET_USERS_DATA = 'GET_USERS_DATA'
export const GET_USERS_DATA_PENDING = 'GET_USERS_DATA_PENDING'
export const GET_USERS_DATA_FULFILLED = 'GET_USERS_DATA_FULFILLED'
export const GET_ROLES_DATA = 'GET_ROLES_DATA'
export const GET_CURRENT_USER_DATA = 'GET_CURRENT_USER_DATA'
export const GET_WAREHOUSES_DATA = 'GET_WAREHOUSES_DATA'
export const GET_WAREHOUSES_DATA_PENDING = 'GET_WAREHOUSES_DATA_PENDING'
export const GET_WAREHOUSES_DATA_FULFILLED = 'GET_WAREHOUSES_DATA_FULFILLED'
export const GET_ALL_BRANCHES_DATA = 'GET_ALL_BRANCHES_DATA'
export const GET_BRANCHES_DATA = 'GET_BRANCHES_DATA'
export const GET_BRANCHES_DATA_PENDING = 'GET_BRANCHES_DATA_PENDING'
export const GET_BRANCHES_DATA_FULFILLED = 'GET_BRANCHES_DATA_FULFILLED'
export const GET_CREDIT_CARDS_DATA = 'GET_CREDIT_CARDS_DATA'
export const GET_CREDIT_CARDS_DATA_PENDING = 'GET_CREDIT_CARDS_DATA_PENDING'
export const GET_CREDIT_CARDS_DATA_FULFILLED = 'GET_CREDIT_CARDS_DATA_FULFILLED'
export const GET_BANK_ACCOUNTS_DATA = 'GET_BANK_ACCOUNTS_DATA'
export const GET_BANK_ACCOUNTS_DATA_PENDING = 'GET_BANK_ACCOUNTS_DATA_PENDING'
export const GET_BANK_ACCOUNTS_DATA_FULFILLED = 'GET_BANK_ACCOUNTS_DATA_FULFILLED'
export const SETTINGS_GET_DWOLLA_BALANCE = 'SETTINGS_GET_DWOLLA_BALANCE'
export const SETTINGS_GET_DWOLLA_BALANCE_PENDING = 'SETTINGS_GET_DWOLLA_BALANCE_PENDING'
export const SETTINGS_GET_DWOLLA_BALANCE_FULFILLED = 'SETTINGS_GET_DWOLLA_BALANCE_FULFILLED'
export const GET_PRODUCTS_WITH_REQUIRED_PARAM =
  'GET_PRODUCTS_WITH_REQUIRED_PARAM'
export const GET_PRODUCTS_WITH_REQUIRED_PARAM_FULFILLED =
  'GET_PRODUCTS_WITH_REQUIRED_PARAM_FULFILLED'
export const SETTINGS_GET_STORED_CSV = 'SETTINGS_GET_STORED_CSV'
export const SETTINGS_GET_STORED_CSV_FULFILLED = 'SETTINGS_GET_STORED_CSV_FULFILLED'
export const PUT_NEW_USER_ROLES_REQUEST = 'PUT_NEW_USER_ROLES_REQUEST'
export const PUT_NEW_USER_ROLES_REQUEST_FULFILLED = 'PUT_NEW_USER_ROLES_REQUEST_FULFILLED'
export const PUT_WAREHOUSE_EDIT_POPUP = 'PUT_WAREHOUSE_EDIT_POPUP'
export const PUT_BRANCHES_EDIT_POPUP = 'PUT_BRANCHES_POPUP'
//export const PUT_PRODUCT_EDIT_POPUP = 'PUT_PRODUCT_EDIT_POPUP'
export const PUT_BANK_ACCOUNT_EDIT_POPUP = 'PUT_BANK_ACCOUNT_EDIT_POPUP'

export const POST_NEW_USER_REQUEST = 'POST_NEW_USER_REQUEST'
export const POST_NEW_USER_REQUEST_FULFILLED = 'POST_NEW_USER_REQUEST_FULFILLED'
export const POST_NEW_WAREHOUSE_POPUP = 'POST_NEW_WAREHOUSE_POPUP'
export const POST_NEW_WAREHOUSE_REQUEST = 'POST_NEW_WAREHOUSE_REQUEST'
export const POST_NEW_BRANCHES_REQUEST = 'POST_NEW_BRANCHES_REQUEST'
export const POST_NEW_CREDIT_CARD_REQUEST = 'POST_NEW_CREDIT_CARD_REQUEST'
export const POST_NEW_BANK_ACCOUNT_REQUEST = 'POST_NEW_BANK_ACCOUNT_REQUEST'
export const POST_NEW_BANK_ACCOUNT_REQUEST_PENDING = 'POST_NEW_BANK_ACCOUNT_REQUEST_PENDING'
export const POST_NEW_BANK_ACCOUNT_REQUEST_REJECTED = 'POST_NEW_BANK_ACCOUNT_REQUEST_REJECTED'
export const POST_NEW_BANK_ACCOUNT_REQUEST_FULFILLED = 'POST_NEW_BANK_ACCOUNT_REQUEST_FULFILLED'
//export const POST_NEW_PRODUCT_REQUEST = 'POST_NEW_PRODUCT_REQUEST'  // ! ! delete
export const POST_UPLOAD_CSV_FILE = 'POST_UPLOAD_CSV_FILE'
export const POST_UPLOAD_CSV_FILE_FULFILLED = 'POST_UPLOAD_CSV_FILE_FULFILLED'

export const GET_CSV_MAP_PRODUCT_OFFER = 'GET_CSV_MAP_PRODUCT_OFFER'
export const GET_CSV_MAP_PRODUCT_OFFER_FULFILLED = 'GET_CSV_MAP_PRODUCT_OFFER_FULFILLED'

export const POST_CSV_MAP_PRODUCT_OFFER = 'POST_CSV_MAP_PRODUCT_OFFER'
export const POST_CSV_MAP_PRODUCT_OFFER_FULFILLED = 'POST_CSV_MAP_PRODUCT_OFFER_FULFILLED'

export const SETTINGS_POST_CSV_IMPORT_PRODUCTS = 'SETTINGS_POST_CSV_IMPORT_PRODUCTS'
export const SETTINGS_POST_CSV_IMPORT_PRODUCTS_FULFILLED = 'SETTINGS_POST_CSV_IMPORT_PRODUCTS_FULFILLED'

export const SETTINGS_POST_CSV_IMPORT_PRODUCTS_OFFER = 'SETTINGS_POST_CSV_IMPORT_PRODUCTS_OFFER'
export const SETTINGS_POST_CSV_IMPORT_PRODUCTS_OFFER_FULFILLED = 'SETTINGS_POST_CSV_IMPORT_PRODUCTS_OFFER_FULFILLED'

export const SETTINGS_CREATE_CAS_PRODUCTS_INDEX = 'SETTINGS_CREATE_CAS_PRODUCTS_INDEX'
export const SETTINGS_REMOVE_CAS_PRODUCTS_INDEX = 'SETTINGS_REMOVE_CAS_PRODUCTS_INDEX'
export const SETTINGS_PREPARE_CAS_PRODUCTS = 'SETTINGS_PREPARE_CAS_PRODUCTS'
export const SEARCH_CAS_PRODUCT = 'SEARCH_CAS_PRODUCT'
export const SEARCH_CAS_PRODUCT_FULFILLED = 'SEARCH_CAS_PRODUCT_FULFILLED'

export const SEARCH_UN_NUMBER = 'SEARCH_UN_NUMBER'
export const SEARCH_UN_NUMBER_FULFILLED = 'SEARCH_UN_NUMBER_FULFILLED'

export const SETTINGS_ADD_ATTACHMENT = 'SETTINGS_ADD_ATTACHMENT'
export const SETTINGS_LOAD_FILE = 'SETTINGS_LOAD_FILE'

export const SETTINGS_REMOVE_ATTACHMENT = 'SETTINGS_REMOVE_ATTACHMENT'
export const SETTINGS_REMOVE_ATTACHMENT_PENDING = 'SETTINGS_REMOVE_ATTACHMENT_PENDING'
export const SETTINGS_REMOVE_ATTACHMENT_FULFILLED = 'SETTINGS_REMOVE_ATTACHMENT_FULFILLED'
export const SETTINGS_REMOVE_ATTACHMENT_REJECTED = 'SETTINGS_REMOVE_ATTACHMENT_REJECTED'



export const SETTINGS_REMOVE_ATTACHMENT_LINK = 'SETTINGS_REMOVE_ATTACHMENT_LINK'

export const SETTINGS_GET_DOCUMENT_TYPES = 'SETTINGS_GET_DOCUMENT_TYPES'
export const SETTINGS_GET_DOCUMENT_TYPES_PENDING = 'SETTINGS_GET_DOCUMENT_TYPES_PENDING'
export const SETTINGS_GET_DOCUMENT_TYPES_FULFILLED = 'SETTINGS_GET_DOCUMENT_TYPES_FULFILLED'
export const SETTINGS_GET_DOCUMENT_TYPES_REJECTED = 'SETTINGS_GET_DOCUMENT_TYPES_REJECTED'

export const SETTINGS_GET_ADDRESSES_SEARCH = 'SETTINGS_GET_ADDRESSES_SEARCH'
export const SETTINGS_GET_ADDRESSES_SEARCH_PENDING = 'SETTINGS_GET_ADDRESSES_SEARCH_PENDING'
export const SETTINGS_GET_ADDRESSES_SEARCH_FULFILLED = 'SETTINGS_GET_ADDRESSES_SEARCH_FULFILLED'
export const SETTINGS_GET_ADDRESSES_SEARCH_REJECTED = 'SETTINGS_GET_ADDRESSES_SEARCH_REJECTED'

export const SETTINGS_GET_DELIVERY_ADDRESSES_BY_STRING = 'SETTINGS_GET_DELIVERY_ADDRESSES_BY_STRING'
export const SETTINGS_GET_DELIVERY_ADDRESSES_BY_STRING_PENDING = 'SETTINGS_GET_DELIVERY_ADDRESSES_BY_STRING_PENDING'
export const SETTINGS_GET_DELIVERY_ADDRESSES_BY_STRING_FULFILLED = 'SETTINGS_GET_DELIVERY_ADDRESSES_BY_STRING_FULFILLED'
export const SETTINGS_GET_DELIVERY_ADDRESSES_BY_STRING_REJECTED = 'SETTINGS_GET_DELIVERY_ADDRESSES_BY_STRING_REJECTED'

export const SETTINGS_GET_DELIVERY_ADDRESSES_BY_FILTER = 'SETTINGS_GET_DELIVERY_ADDRESSES_BY_FILTER'
export const SETTINGS_GET_DELIVERY_ADDRESSES_BY_FILTER_PENDING = 'SETTINGS_GET_DELIVERY_ADDRESSES_BY_FILTER_PENDING'
export const SETTINGS_GET_DELIVERY_ADDRESSES_BY_FILTER_FULFILLED = 'SETTINGS_GET_DELIVERY_ADDRESSES_BY_FILTER_FULFILLED'
export const SETTINGS_GET_DELIVERY_ADDRESSES_BY_FILTER_REJECTED = 'SETTINGS_GET_DELIVERY_ADDRESSES_BY_FILTER_REJECTED'

export const SETTINGS_DELETE_DELIVERY_ADDRESSES = 'SETTINGS_DELETE_DELIVERY_ADDRESSES'
export const SETTINGS_DELETE_DELIVERY_ADDRESSES_PENDING = 'SETTINGS_DELETE_DELIVERY_ADDRESSES_PENDING'
export const SETTINGS_DELETE_DELIVERY_ADDRESSES_FULFILLED = 'SETTINGS_DELETE_DELIVERY_ADDRESSES_FULFILLED'
export const SETTINGS_DELETE_DELIVERY_ADDRESSES_REJECTED = 'SETTINGS_DELETE_DELIVERY_ADDRESSES_REJECTED'

export const SETTINGS_GET_COUNTRIES = 'SETTINGS_GET_COUNTRIES'
export const SETTINGS_GET_COUNTRIES_PENDING = 'SETTINGS_GET_COUNTRIES_PENDING'
export const SETTINGS_GET_COUNTRIES_FULFILLED = 'SETTINGS_GET_COUNTRIES_FULFILLED'
export const SETTINGS_GET_COUNTRIES_REJECTED = 'SETTINGS_GET_COUNTRIES_REJECTED'

export const SETTINGS_GET_PROVINCES = 'SETTINGS_GET_PROVINCES'
export const SETTINGS_GET_PROVINCES_PENDING = 'SETTINGS_GET_PROVINCES_PENDING'
export const SETTINGS_GET_PROVINCES_FULFILLED = 'SETTINGS_GET_PROVINCES_FULFILLED'
export const SETTINGS_GET_PROVINCES_REJECTED = 'SETTINGS_GET_PROVINCES_REJECTED'

export const SETTINGS_UPDATE_DELIVERY_ADDRESSES = 'SETTINGS_UPDATE_DELIVERY_ADDRESSES'
export const SETTINGS_UPDATE_DELIVERY_ADDRESSES_PENDING = 'SETTINGS_UPDATE_DELIVERY_ADDRESSES_PENDING'
export const SETTINGS_UPDATE_DELIVERY_ADDRESSES_FULFILLED = 'SETTINGS_UPDATE_DELIVERY_ADDRESSES_FULFILLED'
export const SETTINGS_UPDATE_DELIVERY_ADDRESSES_REJECTED = 'SETTINGS_UPDATE_DELIVERY_ADDRESSES_REJECTED'

export const SETTINGS_CREATE_NEW_DELIVERY_ADDRESS = 'SETTINGS_CREATE_NEW_DELIVERY_ADDRESS'
export const SETTINGS_CREATE_NEW_DELIVERY_ADDRESS_PENDING = 'SETTINGS_CREATE_NEW_DELIVERY_ADDRESS_PENDING'
export const SETTINGS_CREATE_NEW_DELIVERY_ADDRESS_FULFILLED = 'SETTINGS_CREATE_NEW_DELIVERY_ADDRESS_FULFILLED'
export const SETTINGS_CREATE_NEW_DELIVERY_ADDRESS_REJECTED = 'SETTINGS_CREATE_NEW_DELIVERY_ADDRESS_REJECTED'

export const SETTINGS_GET_PRODUCTS_CATALOG_DATA = 'SETTINGS_GET_PRODUCTS_CATALOG_DATA'
export const SETTINGS_GET_PRODUCTS_CATALOG_DATA_PENDING = 'SETTINGS_GET_PRODUCTS_CATALOG_DATA_PENDING'
export const SETTINGS_GET_PRODUCTS_CATALOG_DATA_FULFILLED = 'SETTINGS_GET_PRODUCTS_CATALOG_DATA_FULFILLED'
export const SETTINGS_GET_PRODUCTS_CATALOG_DATA_REJECTED = 'SETTINGS_GET_PRODUCTS_CATALOG_DATA_REJECTED'

export const SETTINGS_POST_NEW_PRODUCT_REQUEST = 'SETTINGS_POST_NEW_PRODUCT_REQUEST'
export const SETTINGS_POST_NEW_PRODUCT_REQUEST_PENDING = 'SETTINGS_POST_NEW_PRODUCT_REQUEST_PENDING'
export const SETTINGS_POST_NEW_PRODUCT_REQUEST_FULFILLED = 'SETTINGS_POST_NEW_PRODUCT_REQUEST_FULFILLED'
export const SETTINGS_POST_NEW_PRODUCT_REQUEST_REJECTED = 'SETTINGS_POST_NEW_PRODUCT_REQUEST_REJECTED'

export const SETTINGS_CREATE_PRODUCT_CATALOG = 'SETTINGS_CREATE_PRODUCT_CATALOG'
export const SETTINGS_CREATE_PRODUCT_CATALOG_PENDING = 'SETTINGS_CREATE_PRODUCT_CATALOG_PENDING'
export const SETTINGS_CREATE_PRODUCT_CATALOG_FULFILLED = 'SETTINGS_CREATE_PRODUCT_CATALOG_FULFILLED'
export const SETTINGS_CREATE_PRODUCT_CATALOG_REJECTED = 'SETTINGS_CREATE_PRODUCT_CATALOG_REJECTED'

export const SETTINGS_UPDATE_PRODUCT_CATALOG = 'SETTINGS_UPDATE_PRODUCT_CATALOG'
export const SETTINGS_UPDATE_PRODUCT_CATALOG_PENDING = 'SETTINGS_UPDATE_PRODUCT_CATALOG_PENDING'
export const SETTINGS_UPDATE_PRODUCT_CATALOG_FULFILLED = 'SETTINGS_UPDATE_PRODUCT_CATALOG_FULFILLED'
export const SETTINGS_UPDATE_PRODUCT_CATALOG_REJECTED = 'SETTINGS_UPDATE_PRODUCT_CATALOG_REJECTED'

export const SETTINGS_CREATE_DWOLLA_ACCOUNT = 'SETTINGS_CREATE_DWOLLA_ACCOUNT'
export const SETTINGS_CREATE_DWOLLA_ACCOUNT_PENDING = 'SETTINGS_CREATE_DWOLLA_ACCOUNT_PENDING'
export const SETTINGS_CREATE_DWOLLA_ACCOUNT_FULFILLED = 'SETTINGS_CREATE_DWOLLA_ACCOUNT_FULFILLED'
export const SETTINGS_CREATE_DWOLLA_ACCOUNT_REJECTED = 'SETTINGS_CREATE_DWOLLA_ACCOUNT_REJECTED'

export const SETTINGS_GET_CURRENCIES = 'SETTINGS_GET_CURRENCIES'
export const SETTINGS_GET_CURRENCIES_PENDING = 'SETTINGS_GET_CURRENCIES_PENDING'
export const SETTINGS_GET_CURRENCIES_FULFILLED = 'SETTINGS_GET_CURRENCIES_FULFILLED'
export const SETTINGS_GET_CURRENCIES_REJECTED = 'SETTINGS_GET_CURRENCIES_REJECTED'

export const USER_SWITCH_ENABLE_DISABLE = 'USER_SWITCH_ENABLE_DISABLE'
export const USER_SWITCH_ENABLE_DISABLE_PENDING = 'USER_SWITCH_ENABLE_DISABLE_PENDING'
export const USER_SWITCH_ENABLE_DISABLE_FULFILLED = 'USER_SWITCH_ENABLE_DISABLE_FULFILLED'
export const USER_SWITCH_ENABLE_DISABLE_REJECTED = 'USER_SWITCH_ENABLE_DISABLE_REJECTED'

export const DWOLLA_START_VERIFICATION = 'DWOLLA_START_VERIFICATION'
export const DWOLLA_START_VERIFICATION_PENDING = 'DWOLLA_START_VERIFICATION_PENDING'
export const DWOLLA_START_VERIFICATION_FULFILLED = 'DWOLLA_START_VERIFICATION_FULFILLED'
export const DWOLLA_FINALIZE_VERIFICATION = 'DWOLLA_FINALIZE_VERIFICATION'
export const DWOLLA_FINALIZE_VERIFICATION_PENDING = 'DWOLLA_FINALIZE_VERIFICATION_PENDING'
export const DWOLLA_FINALIZE_VERIFICATION_FULFILLED = 'DWOLLA_FINALIZE_VERIFICATION_FULFILLED'

export const ADD_TAB = 'ADD_TAB'

export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_PENDING = 'DELETE_USER_PENDING'
export const DELETE_USER_FULFILLED = 'DELETE_USER_FULFILLED'
export const DELETE_USER_REJECTED = 'DELETE_USER_REJECTED'

export const DELETE_BRANCH = 'DELETE_BRANCH'
export const DELETE_BRANCH_PENDING = 'DELETE_BRANCH_PENDING'
export const DELETE_BRANCH_FULFILLED = 'DELETE_BRANCH_FULFILLED'
export const DELETE_BRANCH_REJECTED = 'DELETE_BRANCH_REJECTED'

export const DELETE_WAREHOUSE = 'DELETE_WAREHOUSE'
export const DELETE_WAREHOUSE_PENDING = 'DELETE_WAREHOUSE_PENDING'
export const DELETE_WAREHOUSE_FULFILLED = 'DELETE_WAREHOUSE_FULFILLED'
export const DELETE_WAREHOUSE_REJECTED = 'DELETE_WAREHOUSE_REJECTED'

export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const DELETE_PRODUCT_PENDING = 'DELETE_PRODUCT_PENDING'
export const DELETE_PRODUCT_FULFILLED = 'DELETE_PRODUCT_FULFILLED'
export const DELETE_PRODUCT_REJECTED = 'DELETE_PRODUCT_REJECTED'

export const DELETE_BANK_ACCOUNT = 'DELETE_BANK_ACCOUNT'
export const DELETE_BANK_ACCOUNT_PENDING = 'DELETE_BANK_ACCOUNT_PENDING'
export const DELETE_BANK_ACCOUNT_FULFILLED = 'DELETE_BANK_ACCOUNT_FULFILLED'
export const DELETE_BANK_ACCOUNT_REJECTED = 'DELETE_BANK_ACCOUNT_REJECTED'

export const TAB_CHANGED = 'TAB_CHANGED'

export const CHANGE_MAP_CSV_NAME = 'CHANGE_MAP_CSV_NAME'

export const SAVE_MAP_CSV = 'SAVE_MAP_CSV'
export const SELECT_SAVED_MAP = 'SELECT_SAVED_MAP'

export const SETTINGS_RESEND_WELCOME_EMAIL = 'SETTINGS_RESEND_WELCOME_EMAIL'

export const GET_LOGISTICS_PROVIDERS = 'GET_LOGISTICS_PROVIDERS'
export const GET_LOGISTICS_PROVIDERS_PENDING = 'GET_LOGISTICS_PROVIDERS_PENDING'
export const GET_LOGISTICS_PROVIDERS_FULFILLED = 'GET_LOGISTICS_PROVIDERS_FULFILLED'
export const GET_LOGISTICS_PROVIDERS_REJECTED = 'GET_LOGISTICS_PROVIDERS_REJECTED'

export const GET_LOGISTICS_ACCOUNTS = 'GET_LOGISTICS_ACCOUNTS'
export const GET_LOGISTICS_ACCOUNTS_PENDING = 'GET_LOGISTICS_ACCOUNTS_PENDING'
export const GET_LOGISTICS_ACCOUNTS_FULFILLED = 'GET_LOGISTICS_ACCOUNTS_FULFILLED'
export const GET_LOGISTICS_ACCOUNTS_REJECTED = 'GET_LOGISTICS_ACCOUNTS_REJECTED'

export const CREATE_LOGISTICS_ACCOUNT = 'CREATE_LOGISTICS_ACCOUNT'
export const CREATE_LOGISTICS_ACCOUNT_PENDING = 'CREATE_LOGISTICS_ACCOUNT_PENDING'
export const CREATE_LOGISTICS_ACCOUNT_FULFILLED = 'CREATE_LOGISTICS_ACCOUNT_FULFILLED'
export const CREATE_LOGISTICS_ACCOUNT_REJECTED = 'CREATE_LOGISTICS_ACCOUNT_REJECTED'

export const UPDATE_LOGISTICS_ACCOUNT = 'UPDATE_LOGISTICS_ACCOUNT'
export const UPDATE_LOGISTICS_ACCOUNT_PENDING = 'UPDATE_LOGISTICS_ACCOUNT_PENDING'
export const UPDATE_LOGISTICS_ACCOUNT_FULFILLED = 'UPDATE_LOGISTICS_ACCOUNT_FULFILLED'
export const UPDATE_LOGISTICS_ACCOUNT_REJECTED = 'UPDATE_LOGISTICS_ACCOUNT_REJECTED'

export const DELETE_LOGISTICS_ACCOUNT = 'DELETE_LOGISTICS_ACCOUNT'
export const DELETE_LOGISTICS_ACCOUNT_PENDING = 'DELETE_LOGISTICS_ACCOUNT_PENDING'
export const DELETE_LOGISTICS_ACCOUNT_FULFILLED = 'DELETE_LOGISTICS_ACCOUNT_FULFILLED'
export const DELETE_LOGISTICS_ACCOUNT_REJECTED = 'DELETE_LOGISTICS_ACCOUNT_REJECTED'

export const RESET_SETTINGS = 'RESET_SETTINGS'


export const GET_SETTINGS = 'GET_SETTINGS'
export const GET_SETTINGS_PENDING = 'GET_SETTINGS_PENDING'
export const GET_SETTINGS_FULFILLED = 'GET_SETTINGS_FULFILLED'
export const GET_SETTINGS_REJECTED = 'GET_SETTINGS_REJECTED'


export const UPDATE_SETTINGS = 'UPDATE_SETTINGS'
export const UPDATE_SETTINGS_PENDING = 'UPDATE_SETTINGS_PENDING'
export const UPDATE_SETTINGS_FULFILLED = 'UPDATE_SETTINGS_FULFILLED'
export const UPDATE_SETTINGS_REJECTED = 'UPDATE_SETTINGS_REJECTED'


export const TRIGGER_SYSTEM_SETTINGS_MODAL = 'TRIGGER_SYSTEM_SETTINGS_MODAL'

export const GET_BUSINESS_CLASSIFICATIONS = 'GET_BUSINESS_CLASSIFICATIONS'
export const GET_BUSINESS_CLASSIFICATIONS_PENDING = 'GET_BUSINESS_CLASSIFICATIONS_PENDING'
export const GET_BUSINESS_CLASSIFICATIONS_FULFILLED = 'GET_BUSINESS_CLASSIFICATIONS_FULFILLED'
export const GET_BUSINESS_CLASSIFICATIONS_REJECTED = 'GET_BUSINESS_CLASSIFICATIONS_REJECTED'

export const TRIGGER_AGREEMENT_MODAL = 'TRIGGER_AGREEMENT_MODAL'

export const SETTINGS_GET_VERIFICATION_DOCUMENT_TYPES = 'SETTINGS_GET_VERIFICATION_DOCUMENT_TYPES'
export const SETTINGS_GET_VERIFICATION_DOCUMENT_TYPES_PENDING = 'SETTINGS_GET_VERIFICATION_DOCUMENT_TYPES_PENDING'
export const SETTINGS_GET_VERIFICATION_DOCUMENT_TYPES_FULFILLED = 'SETTINGS_GET_VERIFICATION_DOCUMENT_TYPES_FULFILLED'
export const SETTINGS_GET_VERIFICATION_DOCUMENT_TYPES_REJECTED = 'SETTINGS_GET_VERIFICATION_DOCUMENT_TYPES_REJECTED'

export const GET_LANGUAGES = 'GET_LANGUAGES'
export const GET_LANGUAGES_PENDING = 'GET_LANGUAGES_PENDING'
export const GET_LANGUAGES_FULFILLED = 'GET_LANGUAGES_FULFILLED'
export const GET_LANGUAGES_REJECTED = 'GET_LANGUAGES_REJECTED'

export const SET_PREFERRED_LANGUAGE = 'SET_PREFERRED_LANGUAGE'
export const SET_PREFERRED_LANGUAGE_PENDING = 'SET_PREFERRED_LANGUAGE_PENDING'
export const SET_PREFERRED_LANGUAGE_FULFILLED = 'SET_PREFERRED_LANGUAGE_FULFILLED'
export const SET_PREFERRED_LANGUAGE_REJECTED = 'SET_PREFERRED_LANGUAGE_REJECTED'

export const SETTINGS_POST_LINK_ATTACHMENT = 'SETTINGS_POST_LINK_ATTACHMENT'
export const SETTINGS_POST_LINK_ATTACHMENT_PENDING = 'SETTINGS_POST_LINK_ATTACHMENT_PENDING'
export const SETTINGS_POST_LINK_ATTACHMENT_FULFILLED = 'SETTINGS_POST_LINK_ATTACHMENT_FULFILLED'
export const SETTINGS_POST_LINK_ATTACHMENT_REJECTED = 'SETTINGS_POST_LINK_ATTACHMENT_REJECTED'

export const SEARCH_ECHO_PRODUCTS = 'SEARCH_ECHO_PRODUCTS'
export const SEARCH_ECHO_PRODUCTS_PENDING = 'SEARCH_ECHO_PRODUCTS_PENDING'
export const SEARCH_ECHO_PRODUCTS_FULFILLED = 'SEARCH_ECHO_PRODUCTS_FULFILLED'
export const SEARCH_ECHO_PRODUCTS_REJECTED = 'SEARCH_ECHO_PRODUCTS_REJECTED'