export const ADD_ZIP = 'ADD_ZIP'
export const ADD_ZIP_PENDING = 'ADD_ZIP_PENDING'
export const ADD_ZIP_REJECTED = 'ADD_ZIP_REJECTED'
export const ADD_ZIP_FULFILLED = 'ADD_ZIP_FULFILLED'

export const GET_ZIP_CODES = 'GET_ZIP_CODES'
export const GET_ZIP_CODES_PENDING = 'GET_ZIP_CODES_PENDING'
export const GET_ZIP_CODES_REJECTED = 'GET_ZIP_CODES_REJECTED'
export const GET_ZIP_CODES_FULFILLED = 'GET_ZIP_CODES_FULFILLED'
