export const PROFILE_OPEN_POPUP = 'PROFILE_OPEN_POPUP'
export const PROFILE_CLOSE_POPUP = 'PROFILE_CLOSE_POPUP'

export const PROFILE_GET_USERS_ME = 'PROFILE_GET_USERS_ME'
export const PROFILE_GET_USERS_ME_PENDING = 'PROFILE_GET_USERS_ME_PENDING'
export const PROFILE_GET_USERS_ME_FULFILLED = 'PROFILE_GET_USERS_ME_FULFILLED'
export const PROFILE_GET_USERS_ME_REJECTED = 'PROFILE_GET_USERS_ME_REJECTED'

export const PROFILE_GET_CURRENCIES = 'PROFILE_GET_CURRENCIES'
export const PROFILE_GET_CURRENCIES_PENDING = 'PROFILE_GET_CURRENCIES_PENDING'
export const PROFILE_GET_CURRENCIES_FULFILLED = 'PROFILE_GET_CURRENCIES_FULFILLED'
export const PROFILE_GET_CURRENCIES_REJECTED = 'PROFILE_GET_CURRENCIES_REJECTED'

export const PROFILE_UPDATE_MY_PROFILE = 'PROFILE_UPDATE_MY_PROFILE'
export const PROFILE_UPDATE_MY_PROFILE_PENDING = 'PROFILE_UPDATE_MY_PROFILE_PENDING'
export const PROFILE_UPDATE_MY_PROFILE_FULFILLED = 'PROFILE_UPDATE_MY_PROFILE_FULFILLED'
export const PROFILE_UPDATE_MY_PROFILE_REJECTED = 'PROFILE_UPDATE_MY_PROFILE_REJECTED'

export const PROFILE_CHANGE_PASSWORD = 'PROFILE_CHANGE_PASSWORD'
export const PROFILE_CHANGE_PASSWORD_PENDING = 'PROFILE_CHANGE_PASSWORD_PENDING'
export const PROFILE_CHANGE_PASSWORD_FULFILLED = 'PROFILE_CHANGE_PASSWORD_FULFILLED'
export const PROFILE_CHANGE_PASSWORD_REJECTED = 'PROFILE_CHANGE_PASSWORD_REJECTED'

export const PROFILE_OPEN_CHANGE_PASSWORD = 'PROFILE_OPEN_CHANGE_PASSWORD'
export const PROFILE_CLOSE_CHANGE_PASSWORD = 'PROFILE_CLOSE_CHANGE_PASSWORD'

//export const PROFILE_ = "PROFILE_"
