export const WB_SIDEBAR_DETAIL_TRIGGER = 'WB_SIDEBAR_DETAIL_TRIGGER'


export const WB_DELETE_WANTED_BOARD_ITEM = 'WB_DELETE_WANTED_BOARD_ITEM'


export const WB_SUBMIT_OFFER_WANTED_BOARD = 'WB_SUBMIT_OFFER_WANTED_BOARD'