export const WB_CLOSE_DETAIL_SIDEBAR = 'WB_CLOSE_DETAIL_SIDEBAR'
export const WB_HANDLE_FILTERS_VALUE = 'WB_HANDLE_FILTERS_VALUE'
export const WB_SIDEBAR_DETAIL_TRIGGER = 'WB_SIDEBAR_DETAIL_TRIGGER'

export const WB_DELETE_WANTED_BOARD_ITEM = 'WB_DELETE_WANTED_BOARD_ITEM'

export const WB_DELETE_MY_OFFER_ITEM = 'WB_DELETE_MY_OFFER_ITEM'

export const WB_OPEN_SUBMIT_OFFER = 'WB_OPEN_SUBMIT_OFFER'
export const WB_CLOSE_POPUP = 'WB_CLOSE_POPUP'

export const WB_PURCHASE_REQUESTED_ITEM = 'WB_PURCHASE_REQUESTED_ITEM'

export const WB_REJECT_REQUESTED_ITEM = 'WB_REJECT_REQUESTED_ITEM'

export const WB_SET_WANTED_BOARD_TYPE = 'WB_SET_WANTED_BOARD_TYPE'
export const WB_SET_MY_REQUESTED_ITEM_TYPE = 'WB_SET_MY_REQUESTED_ITEM_TYPE'

export const WB_GET_AUTOCOMPLETE_DATA = 'WB_GET_AUTOCOMPLETE_DATA'
export const WB_GET_AUTOCOMPLETE_DATA_PENDING = 'WB_GET_AUTOCOMPLETE_DATA_PENDING'
export const WB_GET_AUTOCOMPLETE_DATA_FULFILLED = 'WB_GET_AUTOCOMPLETE_DATA_FULFILLED'
export const WB_GET_AUTOCOMPLETE_DATA_REJECTED = 'WB_GET_AUTOCOMPLETE_DATA_REJECTED'

export const WB_GET_PACKAGING_TYPES = 'WB_GET_PACKAGING_TYPES'
export const WB_GET_PACKAGING_TYPES_PENDING = 'WB_GET_PACKAGING_TYPES_PENDING'
export const WB_GET_PACKAGING_TYPES_FULFILLED = 'WB_GET_PACKAGING_TYPES_FULFILLED'
export const WB_GET_PACKAGING_TYPES_REJECTED = 'WB_GET_PACKAGING_TYPES_REJECTED'

export const WB_SEARCH_MANUFACTURERS = 'WB_SEARCH_MANUFACTURERS'
export const WB_SEARCH_MANUFACTURERS_PENDING = 'WB_SEARCH_MANUFACTURERS_PENDING'
export const WB_SEARCH_MANUFACTURERS_FULFILLED = 'WB_SEARCH_MANUFACTURERS_FULFILLED'
export const WB_SEARCH_MANUFACTURERS_REJECTED = 'WB_SEARCH_MANUFACTURERS_REJECTED'

export const WB_SEARCH_CAS_NUMBER = 'WB_SEARCH_CAS_NUMBER'
export const WB_SEARCH_CAS_NUMBER_PENDING = 'WB_SEARCH_CAS_NUMBER_PENDING'
export const WB_SEARCH_CAS_NUMBER_FULFILLED = 'WB_SEARCH_CAS_NUMBER_FULFILLED'
export const WB_SEARCH_CAS_NUMBER_REJECTED = 'WB_SEARCH_CAS_NUMBER_REJECTED'

export const WB_GET_CONDITIONS = 'WB_GET_CONDITIONS'
export const WB_GET_CONDITIONS_PENDING = 'WB_GET_CONDITIONS_PENDING'
export const WB_GET_CONDITIONS_FULFILLED = 'WB_GET_CONDITIONS_FULFILLED'
export const WB_GET_CONDITIONS_REJECTED = 'WB_GET_CONDITIONS_REJECTED'

export const WB_GET_COUNTRIES = 'WB_GET_COUNTRIES'
export const WB_GET_COUNTRIES_PENDING = 'WB_GET_COUNTRIES_PENDING'
export const WB_GET_COUNTRIES_FULFILLED = 'WB_GET_COUNTRIES_FULFILLED'
export const WB_GET_COUNTRIES_REJECTED = 'WB_GET_COUNTRIES_REJECTED'

export const WB_GET_PROVINCES = 'WB_GET_PROVINCES'
export const WB_GET_PROVINCES_PENDING = 'WB_GET_PROVINCES_PENDING'
export const WB_GET_PROVINCES_FULFILLED = 'WB_GET_PROVINCES_FULFILLED'
export const WB_GET_PROVINCES_REJECTED = 'WB_GET_PROVINCES_REJECTED'

export const WB_GET_FORMS = 'WB_GET_FORMS'
export const WB_GET_FORMS_PENDING = 'WB_GET_FORMS_PENDING'
export const WB_GET_FORMS_FULFILLED = 'WB_GET_FORMS_FULFILLED'
export const WB_GET_FORMS_REJECTED = 'WB_GET_FORMS_REJECTED'

export const WB_GET_GRADES = 'WB_GET_GRADES'
export const WB_GET_GRADES_PENDING = 'WB_GET_GRADES_PENDING'
export const WB_GET_GRADES_FULFILLED = 'WB_GET_GRADES_FULFILLED'
export const WB_GET_GRADES_REJECTED = 'WB_GET_GRADES_REJECTED'

export const WB_GET_UNITS = 'WB_GET_UNITS'
export const WB_GET_UNITS_PENDING = 'WB_GET_UNITS_PENDING'
export const WB_GET_UNITS_FULFILLED = 'WB_GET_UNITS_FULFILLED'
export const WB_GET_UNITS_REJECTED = 'WB_GET_UNITS_REJECTED'

export const WB_GET_WAREHOUSES = 'WB_GET_WAREHOUSES'
export const WB_GET_WAREHOUSES_PENDING = 'WB_GET_WAREHOUSES_PENDING'
export const WB_GET_WAREHOUSES_FULFILLED = 'WB_GET_WAREHOUSES_FULFILLED'
export const WB_GET_WAREHOUSES_REJECTED = 'WB_GET_WAREHOUSES_REJECTED'

export const WB_ADD_PURCHASE_REQUEST = 'WB_ADD_PURCHASE_REQUEST'
export const WB_ADD_PURCHASE_REQUEST_PENDING = 'WB_ADD_PURCHASE_REQUEST_PENDING'
export const WB_ADD_PURCHASE_REQUEST_FULFILLED = 'WB_ADD_PURCHASE_REQUEST_FULFILLED'
export const WB_ADD_PURCHASE_REQUEST_REJECTED = 'WB_ADD_PURCHASE_REQUEST_REJECTED'

export const WB_EDIT_PURCHASE_REQUEST = 'WB_EDIT_PURCHASE_REQUEST'
export const WB_EDIT_PURCHASE_REQUEST_PENDING = 'WB_EDIT_PURCHASE_REQUEST_PENDING'
export const WB_EDIT_PURCHASE_REQUEST_FULFILLED = 'WB_EDIT_PURCHASE_REQUEST_FULFILLED'
export const WB_EDIT_PURCHASE_REQUEST_REJECTED = 'WB_EDIT_PURCHASE_REQUEST_REJECTED'

export const WB_GET_MATCHING_PRODUCT_OFFERS = 'WB_GET_MATCHING_PRODUCT_OFFERS'
export const WB_GET_MATCHING_PRODUCT_OFFERS_PENDING = 'WB_GET_MATCHING_PRODUCT_OFFERS_PENDING'
export const WB_GET_MATCHING_PRODUCT_OFFERS_FULFILLED = 'WB_GET_MATCHING_PRODUCT_OFFERS_FULFILLED'
export const WB_GET_MATCHING_PRODUCT_OFFERS_REJECTED = 'WB_GET_MATCHING_PRODUCT_OFFERS_REJECTED'