export const BROADCAST_FETCH_FAILED = "BROADCAST_FETCH_FAILED";
export const BROADCAST_FETCH_REQUESTED = "BROADCAST_FETCH_REQUESTED";
export const BROADCAST_FETCH_SUCCEEDED = "BROADCAST_FETCH_SUCCEEDED";