export const BROADCAST_FETCH_FAILED = 'BROADCAST_FETCH_FAILED'
export const BROADCAST_FETCH_REQUESTED = 'BROADCAST_FETCH_REQUESTED'
export const BROADCAST_FETCH_SUCCEEDED = 'BROADCAST_FETCH_SUCCEEDED'

export const BROADCAST_POST_FAILED = 'BROADCAST_POST_FAILED'
export const BROADCAST_POST_REQUESTED = 'BROADCAST_POST_REQUESTED'
export const BROADCAST_POST_SUCCEEDED = 'BROADCAST_POST_SUCCEEDED'

//refactor

export const GET_BROADCAST_REQUESTED = 'GET_BROADCAST_REQUESTED'
export const GET_BROADCAST_SUCCEEDED = 'GET_BROADCAST_SUCCEEDED'
export const GET_BROADCAST_FAILED = 'GET_BROADCAST_FAILED'

export const POST_BROADCAST_REQUESTED = 'BROADCAST_FETCH_REQUESTED'
export const POST_BROADCAST_SUCCEEDED = 'BROADCAST_FETCH_SUCCEEDED'
export const POST_BROADCAST_FAILED = 'BROADCAST_FETCH_FAILED'
