export const BROADCAST_FETCH_FAILED = "BROADCAST_FETCH_FAILED";
export const BROADCAST_FETCH_REQUESTED = "BROADCAST_FETCH_REQUESTED";
export const BROADCAST_FETCH_SUCCEEDED = "BROADCAST_FETCH_SUCCEEDED";

export const BROADCAST_POST_FAILED = "BROADCAST_POST_FAILED";
export const BROADCAST_POST_REQUESTED = "BROADCAST_POST_REQUESTED";
export const BROADCAST_POST_SUCCEEDED = "BROADCAST_POST_SUCCEEDED";