export const OFFER_FETCH_FAILED = 'OFFER_FETCH_FAILED'
export const OFFER_FETCH_REQUESTED = 'OFFER_FETCH_REQUESTED'
export const OFFER_FETCH_SUCCEEDED = 'OFFER_FETCH_SUCCEEDED'

export const CART_FETCH_FAILED = 'CART_FETCH_FAILED'
export const CART_FETCH_REQUESTED = 'CART_FETCH_REQUESTED'
export const CART_FETCH_REQUESTED_FULFILLED = 'CART_FETCH_REQUESTED_FULFILLED'

export const DELIVERYADDRESSES_FETCH_REQUESTED = 'DELIVERYADDRESSES_FETCH_REQUESTED' 
export const DELIVERYADDRESSES_FETCH_FAILED = 'DELIVERYADDRESSES_FETCH_FAILED'
export const DELIVERYADDRESSES_FETCH_SUCCEEDED = 'DELIVERYADDRESSES_FETCH_SUCCEEDED'

export const PRODUCTFROMCART_REMOVE_REQUESTED = 'PRODUCTFROMCART_REMOVE_REQUESTED'
export const PRODUCTFROMCART_REMOVE_FAILED = 'PRODUCTFROMCART_REMOVE_FAILED'
export const PRODUCTFROMCART_REMOVE_SUCCEEDED = 'PRODUCTFROMCART_REMOVE_SUCCEEDED'

export const CARTITEM_CREATE_REQUESTED = 'CARTITEM_CREATE_REQUESTED'
export const CARTITEM_CREATE_FAILED = 'CARTITEM_CREATE_FAILED'
export const CARTITEM_CREATE_SUCCEEDED = 'CARTITEM_CREATE_SUCCEEDED'

export const PAYMENTS_FETCH_FAILED = 'PAYMENTS_FETCH_FAILED'
export const PAYMENTS_FETCH_REQUESTED = 'PAYMENTS_FETCH_REQUESTED'
export const PAYMENTS_FETCH_SUCCEEDED = 'PAYMENTS_FETCH_SUCCEEDED'

export const DELIVERYADDRESS_CREATE_REQUESTED = 'DELIVERYADDRESS_CREATE_REQUESTED'
export const DELIVERYADDRESS_CREATE_FAILED = 'DELIVERYADDRESS_CREATE_FAILED'
export const DELIVERYADDRESS_CREATE_SUCCEEDED = 'DELIVERYADDRESS_CREATE_SUCCEEDED'

export const ORDERDETAIL_FETCH_REQUESTED = 'ORDERDETAIL_FETCH_REQUESTED'
export const ORDERDETAIL_FETCH_FAILED = 'ORDERDETAIL_FETCH_FAILED'
export const ORDERDETAIL_FETCH_SUCCEEDED = 'ORDERDETAIL_FETCH_SUCCEEDED'

export const ORDER_EDIT_SUCCEEDED = 'ORDER_EDIT_SUCCEEDED'
export const ORDER_EDIT_FAILED = 'ORDER_EDIT_FAILED'
export const ORDER_EDIT_REQUESTED = 'ORDER_EDIT_REQUESTED'

export const DELIVERYADDRESS_EDIT_SUCCEEDED = 'DELIVERYADDRESS_EDIT_SUCCEEDED'
export const DELIVERYADDRESS_EDIT_FAILED = 'DELIVERYADDRESS_EDIT_FAILED'
export const DELIVERYADDRESS_EDIT_REQUESTED = 'DELIVERYADDRESS_EDIT_REQUESTED'

export const SHIPPING_QUOTES_FETCH_SUCCEEDED = 'SHIPPING_QUOTES_FETCH_SUCCEEDED'
export const SHIPPING_QUOTES_FETCH_FAILED = 'SHIPPING_QUOTES_FETCH_FAILED'
export const SHIPPING_QUOTES_FETCH_REQUESTED = 'SHIPPING_QUOTES_FETCH_REQUESTED'

export const GET_CART_REQUESTED = 'GET_CART_REQUESTED'
export const GET_CART_SUCCEEDED = 'GET_CART_SUCCEEDED'
export const GET_CART_FAILED = 'GET_CART_FAILED'

export const DELETE_CART_REQUESTED = 'DELETE_CART_REQUESTED'
export const DELETE_CART_SUCCEEDED = 'DELETE_CART_SUCCEEDED'
export const DELETE_CART_FAILED = 'DELETE_CART_FAILED'

export const ADD_CART_ITEM_REQUESTED = 'ADD_CART_ITEM_REQUESTED'
export const ADD_CART_ITEM_SUCCEEDED = 'ADD_CART_ITEM_SUCCEEDED'
export const ADD_CART_ITEM_FAILED = 'ADD_CART_ITEM_FAILED'

export const DELETE_CART_ITEM_REQUESTED = 'DELETE_CART_ITEM_REQUESTED'
export const DELETE_CART_ITEM_SUCCEEDED = 'DELETE_CART_ITEM_SUCCEEDED'
export const DELETE_CART_ITEM_FAILED = 'DELETE_CART_ITEM_FAILED'

export const UPDATE_CART_ITEM_REQUESTED = 'UPDATE_CART_ITEM_REQUESTED'
export const UPDATE_CART_ITEM_SUCCEEDED = 'UPDATE_CART_ITEM_SUCCEEDED'
export const UPDATE_CART_ITEM_FAILED = 'UPDATE_CART_ITEM_FAILED'

export const GET_CART_ITEM_REQUESTED = 'GET_CART_ITEM_REQUESTED'
export const GET_CART_ITEM_SUCCEEDED = 'GET_CART_ITEM_SUCCEEDED'
export const GET_CART_ITEM_FAILED = 'GET_CART_ITEM_FAILED'

export const SIDEBAR_CHANGED = 'SIDEBAR_CHANGED'


export const SHIPPING_QUOTE_SELECTED= 'SHIPPING_QUOTE_SELECTED'


/*
export const POST_NEW_ORDER_REQUESTED = 'POST_NEW_ORDER_REQUESTED'
export const POST_NEW_ORDER_SUCCEEDED = 'POST_NEW_ORDER_SUCCEEDED'
export const POST_NEW_ORDER_FAILED = 'POST_NEW_ORDER_FAILED'

export const OFFER_FETCH_FAILED = 'OFFER_FETCH_FAILED'
export const OFFER_FETCH_REQUESTED = 'OFFER_FETCH_REQUESTED'
export const OFFER_FETCH_SUCCEEDED = 'OFFER_FETCH_SUCCEEDED'

export const OFFER_FETCH_FAILED = 'OFFER_FETCH_FAILED'
export const OFFER_FETCH_REQUESTED = 'OFFER_FETCH_REQUESTED'
export const OFFER_FETCH_SUCCEEDED = 'OFFER_FETCH_SUCCEEDED'

export const OFFER_FETCH_FAILED = 'OFFER_FETCH_FAILED'
export const OFFER_FETCH_REQUESTED = 'OFFER_FETCH_REQUESTED'
export const OFFER_FETCH_SUCCEEDED = 'OFFER_FETCH_SUCCEEDED'

export const OFFER_FETCH_FAILED = 'OFFER_FETCH_FAILED'
export const OFFER_FETCH_REQUESTED = 'OFFER_FETCH_REQUESTED'
export const OFFER_FETCH_SUCCEEDED = 'OFFER_FETCH_SUCCEEDED'

export const OFFER_FETCH_FAILED = 'OFFER_FETCH_FAILED'
export const OFFER_FETCH_REQUESTED = 'OFFER_FETCH_REQUESTED'
export const OFFER_FETCH_SUCCEEDED = 'OFFER_FETCH_SUCCEEDED'

export const OFFER_FETCH_FAILED = 'OFFER_FETCH_FAILED'
export const OFFER_FETCH_REQUESTED = 'OFFER_FETCH_REQUESTED'
export const OFFER_FETCH_SUCCEEDED = 'OFFER_FETCH_SUCCEEDED'

export const OFFER_FETCH_FAILED = 'OFFER_FETCH_FAILED'
export const OFFER_FETCH_REQUESTED = 'OFFER_FETCH_REQUESTED'
export const OFFER_FETCH_SUCCEEDED = 'OFFER_FETCH_SUCCEEDED'

export const OFFER_FETCH_FAILED = 'OFFER_FETCH_FAILED'
export const OFFER_FETCH_REQUESTED = 'OFFER_FETCH_REQUESTED'
export const OFFER_FETCH_SUCCEEDED = 'OFFER_FETCH_SUCCEEDED'

*/
