export const OFFER_FETCH_FAILED = "OFFER_FETCH_FAILED";
export const OFFER_FETCH_REQUESTED = "OFFER_FETCH_REQUESTED";
export const OFFER_FETCH_SUCCEEDED = "OFFER_FETCH_SUCCEEDED";

export const CARTITEMS_FETCH_FAILED = "CARTITEMS_FETCH_FAILED";
export const CARTITEMS_FETCH_REQUESTED = "CARTITEMS_FETCH_REQUESTED";
export const CARTITEMS_FETCH_SUCCEEDED = "CARTITEMS_FETCH_SUCCEEDED";

export const DELIVERYADDRESSES_FETCH_REQUESTED = "DELIVERYADDRESSES_FETCH_REQUESTED"; 
export const DELIVERYADDRESSES_FETCH_FAILED = "DELIVERYADDRESSES_FETCH_FAILED";
export const DELIVERYADDRESSES_FETCH_SUCCEEDED = "DELIVERYADDRESSES_FETCH_SUCCEEDED";
