export const COMPANIES_FETCH_REQUESTED = 'COMPANIES_FETCH_REQUESTED';
export const COMPANIES_FETCH_FAILED = 'COMPANIES_FETCH_FAILED';
export const COMPANIES_FETCH_SUCCEEDED = 'COMPANIES_FETCH_SUCCEEDED';
