export const REGIONS_FETCH_REQUESTED = 'REGIONS_FETCH_REQUESTED';
export const REGIONS_FETCH_FAILED = 'REGIONS_FETCH_FAILED';
export const REGIONS_FETCH_SUCCEEDED = 'REGIONS_FETCH_SUCCEEDED';

export const STATES_FETCH_REQUESTED = 'STATES_FETCH_REQUESTED';
export const STATES_FETCH_FAILED = 'STATES_FETCH_FAILED';
export const STATES_FETCH_SUCCEEDED = 'STATES_FETCH_SUCCEEDED';

export const STATEDETAIL_FETCH_REQUESTED = 'STATEDETAIL_FETCH_REQUESTED';
export const STATEDETAIL_FETCH_FAILED = 'STATEDETAIL_FETCH_FAILED';
export const STATEDETAIL_FETCH_SUCCEEDED = 'STATEDETAIL_FETCH_SUCCEEDED';