export const MERCHANT_FETCH_REQUESTED = 'MERCHANT_FETCH_REQUESTED'
export const MERCHANT_FETCH_FAILED = 'MERCHANT_FETCH_FAILED'
export const MERCHANT_FETCH_SUCCEEDED = 'MERCHANT_FETCH_SUCCEEDED'

export const MERCHANT_EDIT_REQUESTED = 'MERCHANT_EDIT_REQUESTED'
export const MERCHANT_EDIT_SUCCEEDED = 'MERCHANT_EDIT_SUCCEEDED'
export const MERCHANT_EDIT_FAILED = 'MERCHANT_EDIT_FAILED'

export const MERCHANTS_FETCH_REQUESTED = 'MERCHANTS_FETCH_REQUESTED'
export const MERCHANTS_FETCH_FAILED = 'MERCHANTS_FETCH_FAILED'
export const MERCHANTS_FETCH_SUCCEEDED = 'MERCHANTS_FETCH_SUCCEEDED'

export const MERCHANT_REMOVE_REQUESTED = 'MERCHANT_REMOVE_REQUESTED'
export const MERCHANT_REMOVE_FAILED = 'MERCHANT_REMOVE_FAILED'
export const MERCHANT_REMOVE_SUCCEEDED = 'MERCHANT_REMOVE_SUCCEEDED'
