export const PRODUCTOFFER_REMOVE_REQUESTED = "PRODUCTOFFER_REMOVE_REQUESTED";
export const PRODUCTOFFER_REMOVE_FAILED = "PRODUCTOFFER_REMOVE_FAILED";
export const PRODUCTOFFER_REMOVE_SUCCEEDED = "PRODUCTOFFER_REMOVE_SUCCEEDED";

export const SHIPPINGQUOTES_FETCH_REQUESTED = "SHIPPINGQUOTES_FETCH_REQUESTED";
export const SHIPPINGQUOTES_FETCH_FAILED = "SHIPPINGQUOTES_FETCH_FAILED";
export const SHIPPINGQUOTES_FETCH_SUCCEEDED = "SHIPPINGQUOTES_FETCH_SUCCEEDED";