export const PRODUCTOFFER_REMOVE_REQUESTED = "PRODUCTOFFER_REMOVE_REQUESTED";
export const PRODUCTOFFER_REMOVE_FAILED = "PRODUCTOFFER_REMOVE_FAILED";
export const PRODUCTOFFER_REMOVE_SUCCEEDED = "PRODUCTOFFER_REMOVE_SUCCEEDED";