export const EDIT_POPUP = 'EDIT_POPUP';
export const SUBMIT_EDIT_POPUP = 'SUBMIT_EDIT_POPUP';
export const DELETE_WAREHOUSE = 'DELETE_WAREHOUSE';
export const ADD_NEW_WAREHOUSE_POPUP = 'ADD_NEW_WAREHOUSE_POPUP';
export const SAVE_NEW_WAREHOUSE = 'SAVE_NEW_WAREHOUSE';
export const ADD_NEW_WAREHOUSE_REQUEST = 'ADD_NEW_WAREHOUSE_REQUEST';