export const SHIPPINGQUOTES_FETCH_REQUESTED = 'SHIPPINGQUOTES_FETCH_REQUESTED'
export const SHIPPINGQUOTES_FETCH_FAILED = 'SHIPPINGQUOTES_FETCH_FAILED'
export const SHIPPINGQUOTES_FETCH_SUCCEEDED = 'SHIPPINGQUOTES_FETCH_SUCCEEDED'
