export const USERS_NEW_FETCH_REQUESTED = 'USERS_NEW_FETCH_REQUESTED';
export const USERS_NEW_FETCH_FAILED = 'USERS_NEW_FETCH_FAILED';
export const USERS_NEW_FETCH_SUCCEEDED = 'USERS_NEW_FETCH_SUCCEEDED';