export const FILTER_NETWORK_STATUS = 'FILTER_NETWORK_STATUS'

export const DISCONNECT = 'DISCONNECT'
export const DISCONNECT_PENDING = 'DISCONNECT_PENDING'
export const DISCONNECT_FULFILLED = 'DISCONNECT_FULFILLED'
export const DISCONNECT_REJECTED = 'DISCONNECT_REJECTED'

export const REJECT = 'REJECT'
export const REJECT_PENDING = 'REJECT_PENDING'
export const REJECT_FULFILLED = 'REJECT_FULFILLED'
export const REJECT_REJECTED = 'REJECT_REJECTED'

export const ACCEPT = 'ACCEPT'
export const ACCEPT_PENDING = 'ACCEPT_PENDING'
export const ACCEPT_FULFILLED = 'ACCEPT_FULFILLED'
export const ACCEPT_REJECTED = 'ACCEPT_REJECTED'
