export const FILTER_NETWORK_STATUS = 'FILTER_NETWORK_STATUS'

export const DISCONNECT = 'DISCONNECT'
export const DISCONNECT_PENDING = 'DISCONNECT_PENDING'
export const DISCONNECT_FULFILLED = 'DISCONNECT_FULFILLED'
export const DISCONNECT_REJECTED = 'DISCONNECT_REJECTED'

export const REJECT = 'REJECT'
export const REJECT_PENDING = 'REJECT_PENDING'
export const REJECT_FULFILLED = 'REJECT_FULFILLED'
export const REJECT_REJECTED = 'REJECT_REJECTED'

export const ACCEPT = 'ACCEPT'
export const ACCEPT_PENDING = 'ACCEPT_PENDING'
export const ACCEPT_FULFILLED = 'ACCEPT_FULFILLED'
export const ACCEPT_REJECTED = 'ACCEPT_REJECTED'

export const REMOVE = 'REMOVE'
export const REMOVE_PENDING = 'REMOVE_PENDING'
export const REMOVE_FULFILLED = 'REMOVE_FULFILLED'
export const REMOVE_REJECTED = 'REMOVE_REJECTED'

export const CONNECTIONS_STATUSES = 'CONNECTIONS_STATUSES'

export const TRIGGER_MODAL = 'TRIGGER_MODAL'

export const SEARCH = 'SEARCH'
export const SEARCH_PENDING = 'SEARCH_PENDING'
export const SEARCH_FULFILLED = 'SEARCH_FULFILLED'
export const SEARCH_REJECTED = 'SEARCH_REJECTED'

export const INVITE = 'INVITE'
export const INVITE_PENDING = 'INVITE_PENDING'
export const INVITE_FULFILLED = 'INVITE_FULFILLED'
export const INVITE_REJECTED = 'INVITE_REJECTED'
