export const ADMIN_OPEN_EDIT_POPUP = 'ADMIN_OPEN_EDIT_POPUP'

export const ADMIN_CLOSE_CONFIRM_POPUP = 'ADMIN_CLOSE_CONFIRM_POPUP'

export const ADMIN_DELETE_CONFIRM_POPUP = 'ADMIN_DELETE_CONFIRM_POPUP'

export const ADMIN_CLOSE_ADD_POPUP = 'ADMIN_CLOSE_ADD_POPUP'

export const ADMIN_DELETE_DOCUMENT_TYPES_DATA = 'ADMIN_DELETE_DOCUMENT_TYPES_DATA'

export const ADMIN_POST_DOCUMENT_TYPES_DATA = 'ADMIN_POST_DOCUMENT_TYPES_DATA'

export const ADMIN_CLOSE_EDIT_POPUP = 'ADMIN_CLOSE_EDIT_POPUP'

export const ADMIN_PUT_DOCUMENT_TYPES_DATA = 'ADMIN_PUT_DOCUMENT_TYPES_DATA'

export const ADMIN_OPEN_POPUP = 'ADMIN_OPEN_POPUP'

export const ADMIN_HANDLE_FILTERS_VALUE = 'ADMIN_HANDLE_FILTERS_VALUE'
