export const DOCUMENT_TYPES_OPEN_EDIT_POPUP = 'DOCUMENT_TYPES_OPEN_EDIT_POPUP'

export const DOCUMENT_TYPES_CLOSE_CONFIRM_POPUP = 'DOCUMENT_TYPES_CLOSE_CONFIRM_POPUP'

export const DOCUMENT_TYPES_DELETE_CONFIRM_POPUP = 'DOCUMENT_TYPES_DELETE_CONFIRM_POPUP'

export const DOCUMENT_TYPES_CLOSE_ADD_POPUP = 'DOCUMENT_TYPES_CLOSE_ADD_POPUP'

export const DOCUMENT_TYPES_DELETE_DOCUMENT_TYPES_DATA = 'DOCUMENT_TYPES_DELETE_DOCUMENT_TYPES_DATA'

export const DOCUMENT_TYPES_POST_DOCUMENT_TYPES_DATA = 'DOCUMENT_TYPES_POST_DOCUMENT_TYPES_DATA'

export const DOCUMENT_TYPES_CLOSE_EDIT_POPUP = 'DOCUMENT_TYPES_CLOSE_EDIT_POPUP'

export const DOCUMENT_TYPES_PUT_DOCUMENT_TYPES_DATA = 'DOCUMENT_TYPES_PUT_DOCUMENT_TYPES_DATA'

export const DOCUMENT_TYPES_OPEN_POPUP = 'DOCUMENT_TYPES_OPEN_POPUP'

export const DOCUMENT_TYPES_HANDLE_FILTERS_VALUE = 'DOCUMENT_TYPES_HANDLE_FILTERS_VALUE'

export const DOCUMENT_TYPES_CLOSE_POPUP = 'DOCUMENT_TYPES_CLOSE_POPUP'

export const DOCUMENT_TYPES_HANDLE_VARIABLE_CHANGE = 'DOCUMENT_TYPES_HANDLE_VARIABLE_CHANGE'