export const ALERTS_TAB_CHANGED = 'ALERTS_TAB_CHANGED'
export const ALERTS_HANDLE_VARIABLE_CHANGE = 'ALERTS_HANDLE_VARIABLE_CHANGE'

export const ALERTS_MARK_SEEN = 'ALERTS_MARK_SEEN'
export const ALERTS_MARK_SEEN_PENDING = 'ALERTS_MARK_SEEN_PENDING'
export const ALERTS_MARK_SEEN_REJECTED = 'ALERTS_MARK_SEEN_REJECTED'
export const ALERTS_MARK_SEEN_FULFILLED = 'ALERTS_MARK_SEEN_FULFILLED'

export const ALERTS_MARK_UNSEEN = 'ALERTS_MARK_UNSEEN'
export const ALERTS_MARK_UNSEEN_PENDING = 'ALERTS_MARK_UNSEEN_PENDING'
export const ALERTS_MARK_UNSEEN_REJECTED = 'ALERTS_MARK_UNSEEN_REJECTED'
export const ALERTS_MARK_UNSEEN_FULFILLED = 'ALERTS_MARK_UNSEEN_FULFILLED'

export const ALERTS_MARK_SEEN_ARRAY = 'ALERTS_MARK_SEEN_ARRAY'
export const ALERTS_MARK_SEEN_ARRAY_PENDING = 'ALERTS_MARK_SEEN_ARRAY_PENDING'
export const ALERTS_MARK_SEEN_ARRAY_REJECTED = 'ALERTS_MARK_SEEN_ARRAY_REJECTED'
export const ALERTS_MARK_SEEN_ARRAY_FULFILLED = 'ALERTS_MARK_SEEN_ARRAY_FULFILLED'

export const ALERTS_MARK_UNSEEN_ARRAY = 'ALERTS_MARK_UNSEEN_ARRAY'
export const ALERTS_MARK_UNSEEN_ARRAY_PENDING = 'ALERTS_MARK_UNSEEN_ARRAY_PENDING'
export const ALERTS_MARK_UNSEEN_ARRAY_REJECTED = 'ALERTS_MARK_UNSEEN_ARRAY_REJECTED'
export const ALERTS_MARK_UNSEEN_ARRAY_FULFILLED = 'ALERTS_MARK_UNSEEN_ARRAY_FULFILLED'

export const ALERTS_DELETE_ARRAY = 'ALERTS_DELETE_ARRAY'
export const ALERTS_DELETE_ARRAY_PENDING = 'ALERTS_DELETE_ARRAY_PENDING'
export const ALERTS_DELETE_ARRAY_REJECTED = 'ALERTS_DELETE_ARRAY_REJECTED'
export const ALERTS_DELETE_ARRAY_FULFILLED = 'ALERTS_DELETE_ARRAY_FULFILLED'

export const ALERTS_GET_CATEGORIES = 'ALERTS_GET_CATEGORIES'
export const ALERTS_GET_CATEGORIES_PENDING = 'ALERTS_GET_CATEGORIES_PENDING'
export const ALERTS_GET_CATEGORIES_REJECTED = 'ALERTS_GET_CATEGORIES_REJECTED'
export const ALERTS_GET_CATEGORIES_FULFILLED = 'ALERTS_GET_CATEGORIES_FULFILLED'

export const ALERTS_GET_COUNT_UNSEEN = 'ALERTS_GET_COUNT_UNSEEN'
export const ALERTS_GET_COUNT_UNSEEN_PENDING = 'ALERTS_GET_COUNT_UNSEEN_PENDING'
export const ALERTS_GET_COUNT_UNSEEN_REJECTED = 'ALERTS_GET_COUNT_UNSEEN_REJECTED'
export const ALERTS_GET_COUNT_UNSEEN_FULFILLED = 'ALERTS_GET_COUNT_UNSEEN_FULFILLED'

export const ALERTS_SET_TYPE = 'ALERTS_SET_TYPE'