export const GET_VELLOCI_TOKEN = 'GET_VELLOCI_TOKEN'
export const GET_VELLOCI_TOKEN_PENDING = 'GET_VELLOCI_TOKEN_PENDING'
export const GET_VELLOCI_TOKEN_FULFILLED = 'GET_VELLOCI_TOKEN_FULFILLED'
export const GET_VELLOCI_TOKEN_REJECTED = 'GET_VELLOCI_TOKEN_REJECTED'

export const ADD_VELLOCI_ACOUNT = 'ADD_VELLOCI_ACOUNT'
export const ADD_VELLOCI_ACOUNT_PENDING = 'ADD_VELLOCI_ACOUNT_PENDING'
export const ADD_VELLOCI_ACOUNT_FULFILLED = 'ADD_VELLOCI_ACOUNT_FULFILLED'
export const ADD_VELLOCI_ACOUNT_REJECTED = 'ADD_VELLOCI_ACOUNT_REJECTED'

export const ON_EVENT_VELLOCI = 'ON_EVENT_VELLOCI'
export const ON_EVENT_VELLOCI_PENDING = 'ON_EVENT_VELLOCI_PENDING'
export const ON_EVENT_VELLOCI_FULFILLED = 'ON_EVENT_VELLOCI_FULFILLED'
export const ON_EVENT_VELLOCI_REJECTED = 'ON_EVENT_VELLOCI_REJECTED'
