FROM node:10-alpine

# Setting working directory. All the path will be relative to WORKDIR
WORKDIR /usr/src/app

# Installing dependencies
COPY package*.json ./
RUN npm install

# Copying source files
COPY . .

#ENV REACT_APP_API_URL=https://test.echoexchange.net/
#ENV NODE_ENV=production
#ENV APP_ENV=review

# Testing app
RUN npm test