export const BUSINESS_TYPES_FETCH = 'BUSINESS_TYPES_FETCH'
export const BUSINESS_TYPES_FETCH_PENDING = 'BUSINESS_TYPES_FETCH_PENDING'
export const BUSINESS_TYPES_FETCH_REJECTED = 'BUSINESS_TYPES_FETCH_REJECTED'
export const BUSINESS_TYPES_FETCH_FULFILLED = 'BUSINESS_TYPES_FETCH_FULFILLED'
