export const BUSINESS_TYPES_FETCH = 'BUSINESS_TYPES_FETCH'
export const BUSINESS_TYPES_FETCH_PENDING = 'BUSINESS_TYPES_FETCH_PENDING'
export const BUSINESS_TYPES_FETCH_REJECTED = 'BUSINESS_TYPES_FETCH_REJECTED'
export const BUSINESS_TYPES_FETCH_FULFILLED = 'BUSINESS_TYPES_FETCH_FULFILLED'

export const GET_COMPANY_LOGO = 'GET_COMPANY_LOGO'
export const GET_COMPANY_LOGO_FULFILLED = 'GET_COMPANY_LOGO_FULFILLED'

export const POST_COMPANY_LOGO = 'POST_COMPANY_LOGO'
export const DELETE_COMPANY_LOGO = 'DELETE_COMPANY_LOGO'
