export const OFFER_FETCH = 'OFFER_FETCH'
export const OFFER_FETCH_PENDING = 'OFFER_FETCH_PENDING' // TODO, PENDING...
export const OFFER_FETCH_REJECTED = 'OFFER_FETCH_REJECTED'
export const OFFER_FETCH_FULFILLED = 'OFFER_FETCH_FULFILLED'

export const STATES_FETCH = 'STATES_FETCH'
export const STATES_FETCH_PENDING = 'STATES_FETCH_PENDING'
export const STATES_FETCH_REJECTED = 'STATES_FETCH_REJECTED'
export const STATES_FETCH_FULFILLED = 'STATES_FETCH_FULFILLED'

export const PROVINCES_FETCH = 'PROVINCES_FETCH'
export const PROVINCES_FETCH_PENDING = 'PROVINCES_FETCH_PENDING'
export const PROVINCES_FETCH_REJECTED = 'PROVINCES_FETCH_REJECTED'
export const PROVINCES_FETCH_FULFILLED = 'PROVINCES_FETCH_FULFILLED'

export const CART_FETCH = 'CART_FETCH'
export const CART_FETCH_PENDING = 'CART_FETCH_PENDING'
export const CART_FETCH_REJECTED = 'CART_FETCH_FAILED'
export const CART_FETCH_FULFILLED = 'CART_FETCH_FULFILLED'

export const DELIVERY_ADDRESS_EDIT = 'DELIVERY_ADDRESS_EDIT'
export const DELIVERY_ADDRESS_EDIT_PENDING = 'DELIVERY_ADDRESS_EDIT_PENDING'
export const DELIVERY_ADDRESS_EDIT_REJECTED = 'DELIVERY_ADDRESS_EDIT_REJECTED'
export const DELIVERY_ADDRESS_EDIT_FULFILLED = 'DELIVERY_ADDRESS_EDIT_FULFILLED'

export const DELIVERY_ADDRESS_CREATE = 'DELIVERY_ADDRESS_CREATE'
export const DELIVERY_ADDRESS_CREATE_PENDING = 'DELIVERY_ADDRESS_CREATE_PENDING'
export const DELIVERY_ADDRESS_CREATE_REJECTED = 'DELIVERY_ADDRESS_CREATE_REJECTED'
export const DELIVERY_ADDRESS_CREATE_FULFILLED = 'DELIVERY_ADDRESS_CREATE_FULFILLED'

export const BRANCHES_FETCH = 'BRANCHES_FETCH'
export const BRANCHES_FETCH_PENDING = 'BRANCHES_FETCH_PENDING'
export const BRANCHES_FETCH_REJECTED = 'BRANCHES_FETCH_REJECTED'
export const BRANCHES_FETCH_FULFILLED = 'BRANCHES_FETCH_FULFILLED'

export const SHIPPING_QUOTES_FETCH = 'SHIPPING_QUOTES_FETCH'
export const SHIPPING_QUOTES_FETCH_PENDING = 'SHIPPING_QUOTES_FETCH_PENDING'
export const SHIPPING_QUOTES_FETCH_REJECTED = 'SHIPPING_QUOTES_FETCH_REJECTED'
export const SHIPPING_QUOTES_FETCH_FULFILLED = 'SHIPPING_QUOTES_FETCH_FULFILLED'

export const ADD_CART_ITEM = 'ADD_CART_ITEM'
export const ADD_CART_ITEM_PENDING = 'ADD_CART_ITEM_PENDING'
export const ADD_CART_ITEM_REJECTED = 'ADD_CART_ITEM_REJECTED'
export const ADD_CART_ITEM_FULFILLED = 'ADD_CART_ITEM_FULFILLED'

export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM'
export const UPDATE_CART_ITEM_PENDING = 'UPDATE_CART_ITEM_PENDING'
export const UPDATE_CART_ITEM_REJECTED = 'UPDATE_CART_ITEM_REJECTED'
export const UPDATE_CART_ITEM_FULFILLED = 'UPDATE_CART_ITEM_FULFILLED'

export const DELETE_CART_ITEM = 'DELETE_CART_ITEM'
export const DELETE_CART_ITEM_PENDING = 'DELETE_CART_ITEM_PENDING'
export const DELETE_CART_ITEM_REJECTED = 'DELETE_CART_ITEM_REJECTED'
export const DELETE_CART_ITEM_FULFILLED = 'DELETE_CART_ITEM_FULFILLED'

export const DELETE_CART = 'DELETE_CART'
export const DELETE_CART_PENDING = 'DELETE_CART_PENDING'
export const DELETE_CART_REJECTED = 'DELETE_CART_REJECTED'
export const DELETE_CART_FULFILLED = 'DELETE_CART_FULFILLED'

export const DELIVERY_ADDRESSES_FETCH = 'DELIVERY_ADDRESSES_FETCH'
export const DELIVERY_ADDRESSES_FETCH_PENDING = 'DELIVERY_ADDRESSES_FETCH_PENDING'
export const DELIVERY_ADDRESSES_FETCH_REJECTED = 'DELIVERY_ADDRESSES_FETCH_REJECTED'
export const DELIVERY_ADDRESSES_FETCH_FULFILLED = 'DELIVERY_ADDRESSES_FETCH_FULFILLED'

export const PAYMENTS_FETCH = 'PAYMENTS_FETCH'
export const PAYMENTS_FETCH_PENDING = 'PAYMENTS_FETCH_PENDING'
export const PAYMENTS_FETCH_REJECTED = 'PAYMENTS_FETCH_REJECTED'
export const PAYMENTS_FETCH_FULFILLED = 'PAYMENTS_FETCH_FULFILLED'

export const POST_PURCHASE_ORDER = 'POST_PURCHASE_ORDER'
export const POST_PURCHASE_ORDER_PENDING = 'POST_PURCHASE_ORDER_PENDING'
export const POST_PURCHASE_ORDER_REJECTED = 'POST_PURCHASE_ORDER_REJECTED'
export const POST_PURCHASE_ORDER_FULFILLED = 'POST_PURCHASE_ORDER_FULFILLED'
// TODO, REFACTOR!

export const PRODUCTFROMCART_REMOVE_REQUESTED = 'PRODUCTFROMCART_REMOVE_REQUESTED'
export const PRODUCTFROMCART_REMOVE_FAILED = 'PRODUCTFROMCART_REMOVE_FAILED'
export const PRODUCTFROMCART_REMOVE_SUCCEEDED = 'PRODUCTFROMCART_REMOVE_SUCCEEDED'

export const CARTITEM_CREATE_REQUESTED = 'CARTITEM_CREATE_REQUESTED'
export const CARTITEM_CREATE_FAILED = 'CARTITEM_CREATE_FAILED'
export const CARTITEM_CREATE_SUCCEEDED = 'CARTITEM_CREATE_SUCCEEDED'

export const ORDERDETAIL_FETCH_REQUESTED = 'ORDERDETAIL_FETCH_REQUESTED'
export const ORDERDETAIL_FETCH_FAILED = 'ORDERDETAIL_FETCH_FAILED'
export const ORDERDETAIL_FETCH_SUCCEEDED = 'ORDERDETAIL_FETCH_SUCCEEDED'

export const ORDER_EDIT_SUCCEEDED = 'ORDER_EDIT_SUCCEEDED'
export const ORDER_EDIT_FAILED = 'ORDER_EDIT_FAILED'
export const ORDER_EDIT_REQUESTED = 'ORDER_EDIT_REQUESTED'

export const GET_CART_REQUESTED = 'GET_CART_REQUESTED'
export const GET_CART_SUCCEEDED = 'GET_CART_SUCCEEDED'
export const GET_CART_FAILED = 'GET_CART_FAILED'

export const GET_CART_ITEM_REQUESTED = 'GET_CART_ITEM_REQUESTED'
export const GET_CART_ITEM_SUCCEEDED = 'GET_CART_ITEM_SUCCEEDED'
export const GET_CART_ITEM_FAILED = 'GET_CART_ITEM_FAILED'

export const SIDEBAR_CHANGED = 'SIDEBAR_CHANGED'

export const SHIPPING_CHANGED = 'SHIPPING_CHANGED'

export const SHIPPING_QUOTE_SELECTED = 'SHIPPING_QUOTE_SELECTED'

export const SET_PRE_FILLED_VALUES = 'SET_PRE_FILLED_VALUES'
export const CLEAR_PRE_FILLED_VALUES = 'CLEAR_PRE_FILLED_VALUES'

export const GET_WAREHOUSES = 'GET_WAREHOUSES'
export const GET_WAREHOUSES_PENDING = 'GET_WAREHOUSES_PENDING'
export const GET_WAREHOUSES_FULFILLED = 'GET_WAREHOUSES_FULFILLED'
export const GET_WAREHOUSES_REJECTED = 'GET_WAREHOUSES_REJECTED'

export const UPDATE_HAZMAT_INFO = 'UPDATE_HAZMAT_INFO'
export const UPDATE_HAZMAT_INFO_PENDING = 'UPDATE_HAZMAT_INFO_PENDING'
export const UPDATE_HAZMAT_INFO_FULFILLED = 'UPDATE_HAZMAT_INFO_FULFILLED'
export const UPDATE_HAZMAT_INFO_REJECTED = 'UPDATE_HAZMAT_INFO_REJECTED'

export const REQUEST_MANUAL_SHIPMENT = 'REQUEST_MANUAL_SHIPMENT'
export const REQUEST_MANUAL_SHIPMENT_PENDING = 'REQUEST_MANUAL_SHIPMENT_PENDING'
export const REQUEST_MANUAL_SHIPMENT_FULFILLED = 'REQUEST_MANUAL_SHIPMENT_FULFILLED'
export const REQUEST_MANUAL_SHIPMENT_REJECTED = 'REQUEST_MANUAL_SHIPMENT_REJECTED'

export const PURCHASE_GET_IDENTITY = 'PURCHASE_GET_IDENTITY'
export const PURCHASE_GET_IDENTITY_PENDING = 'PURCHASE_GET_IDENTITY_PENDING'
export const PURCHASE_GET_IDENTITY_FULFILLED = 'PURCHASE_GET_IDENTITY_FULFILLED'
export const PURCHASE_GET_IDENTITY_REJECTED = 'PURCHASE_GET_IDENTITY_REJECTED'