export const GUESTS_OPEN_POPUP = 'GUESTS_OPEN_POPUP'
export const GUESTS_CLOSE_POPUP = 'GUESTS_CLOSE_POPUP'
export const GUESTS_TAB_CHANGED = 'GUESTS_TAB_CHANGED'

export const GUESTS_OPEN_COMPANY_EDIT = 'GUESTS_OPEN_COMPANY_EDIT'
export const GUESTS_CLOSE_COMPANY_EDIT = 'GUESTS_CLOSE_COMPANY_EDIT'
export const GUESTS_COMPANY_EDIT_TAB_CHANGED = 'GUESTS_COMPANY_EDIT_TAB_CHANGED'

export const GUESTS_HANDLE_VARIABLE_CHANGE = 'GUESTS_HANDLE_VARIABLE_CHANGE'

export const GUESTS_DELETE_CLIENT_COMPANY = 'GUESTS_DELETE_CLIENT_COMPANY'
export const GUESTS_DELETE_CLIENT_COMPANY_PENDING = 'GUESTS_DELETE_CLIENT_COMPANY_PENDING'
export const GUESTS_DELETE_CLIENT_COMPANY_REJECTED = 'GUESTS_DELETE_CLIENT_COMPANY_REJECTED'
export const GUESTS_DELETE_CLIENT_COMPANY_FULFILLED = 'GUESTS_DELETE_CLIENT_COMPANY_FULFILLED'

export const GUESTS_GET_DOCUMENT_TYPES = 'GUESTS_GET_DOCUMENT_TYPES'
export const GUESTS_GET_DOCUMENT_TYPES_PENDING = 'GUESTS_GET_DOCUMENT_TYPES_PENDING'
export const GUESTS_GET_DOCUMENT_TYPES_REJECTED = 'GUESTS_GET_DOCUMENT_TYPES_REJECTED'
export const GUESTS_GET_DOCUMENT_TYPES_FULFILLED = 'GUESTS_GET_DOCUMENT_TYPES_FULFILLED'

export const GUESTS_GET_CLIENT_COMPANY_ROLES = 'GUESTS_GET_CLIENT_COMPANY_ROLES'
export const GUESTS_GET_CLIENT_COMPANY_ROLES_PENDING = 'GUESTS_GET_CLIENT_COMPANY_ROLES_PENDING'
export const GUESTS_GET_CLIENT_COMPANY_ROLES_REJECTED = 'GUESTS_GET_CLIENT_COMPANY_ROLES_REJECTED'
export const GUESTS_GET_CLIENT_COMPANY_ROLES_FULFILLED = 'GUESTS_GET_CLIENT_COMPANY_ROLES_FULFILLED'

export const GUESTS_CREATE_CLIENT_COMPANY = 'GUESTS_CREATE_CLIENT_COMPANY'
export const GUESTS_CREATE_CLIENT_COMPANY_PENDING = 'GUESTS_CREATE_CLIENT_COMPANY_PENDING'
export const GUESTS_CREATE_CLIENT_COMPANY_REJECTED = 'GUESTS_CREATE_CLIENT_COMPANY_REJECTED'
export const GUESTS_CREATE_CLIENT_COMPANY_FULFILLED = 'GUESTS_CREATE_CLIENT_COMPANY_FULFILLED'

export const GUESTS_ADD_NEW_USER = 'GUESTS_ADD_NEW_USER'
export const GUESTS_ADD_NEW_USER_PENDING = 'GUESTS_ADD_NEW_USER_PENDING'
export const GUESTS_ADD_NEW_USER_REJECTED = 'GUESTS_ADD_NEW_USER_REJECTED'
export const GUESTS_ADD_NEW_USER_FULFILLED = 'GUESTS_ADD_NEW_USER_FULFILLED'

export const GUESTS_EDIT_USER = 'GUESTS_EDIT_USER'
export const GUESTS_EDIT_USER_PENDING = 'GUESTS_EDIT_USER_PENDING'
export const GUESTS_EDIT_USER_REJECTED = 'GUESTS_EDIT_USER_REJECTED'
export const GUESTS_EDIT_USER_FULFILLED = 'GUESTS_EDIT_USER_FULFILLED'

export const GUESTS_DELETE_USER = 'GUESTS_DELETE_USER'
export const GUESTS_DELETE_USER_PENDING = 'GUESTS_DELETE_USER_PENDING'
export const GUESTS_DELETE_USER_REJECTED = 'GUESTS_DELETE_USER_REJECTED'
export const GUESTS_DELETE_USER_FULFILLED = 'GUESTS_DELETE_USER_FULFILLED'