export const MARKETPLACE_FIND_PRODUCTS = "MARKETPLACE_FIND_PRODUCTS"
export const MARKETPLACE_SEARCH_PRODUCTS = "MARKETPLACE_SEARCH_PRODUCTS"
export const MARKETPLACE_SEARCH_PRODUCTS_PENDING = "MARKETPLACE_SEARCH_PRODUCTS_PENDING"
export const MARKETPLACE_SEARCH_PRODUCTS_FULFILLED = "MARKETPLACE_SEARCH_PRODUCTS_FULFILLED"

export const GET_BROADCASTED_FILTERS = 'GET_BROADCASTED_FILTERS'
export const GET_BROADCASTED_FILTERS_PENDING = 'GET_BROADCASTED_FILTERS_PENDING'
export const GET_BROADCASTED_FILTERS_FULFILLED = 'GET_BROADCASTED_FILTERS_FULFILLED'
export const GET_BROADCASTED_FILTERS_REJECTED = 'GET_BROADCASTED_FILTERS_REJECTED'

export const SAVE_BROADCASTED_FILTER = 'SAVE_BROADCASTED_FILTER'
export const SAVE_BROADCASTED_FILTER_PENDING = 'SAVE_BROADCASTED_FILTER_PENDING'
export const SAVE_BROADCASTED_FILTER_FULFILLED = 'SAVE_BROADCASTED_FILTER_FULFILLED'
export const SAVE_BROADCASTED_FILTER_REJECTED = 'SAVE_BROADCASTED_FILTER_REJECTED'