import { createAction, createAsyncAction } from 'redux-promise-middleware-actions'
// Apis
import * as api from './api'

export const findProducts = createAsyncAction('MARKETPLACE_FIND_PRODUCTS', (search) => api.findProducts(search))
export const getAutocompleteData = createAsyncAction('GET_AUTOCOMPLETE_DATA_MARKETPLACE', ({ searchQuery }) => api.getAutocompleteData(searchQuery))
export const clearAutocompleteData = createAction('CLEAR_AUTOCOMPLETE_DATA', () => ({}))
export const applyDatagridFilter = createAction('MARKETPLACE_APPLY_FILTER', (filter, reload = true) => ({ filter, reload }))
export const handleVariableSave = createAction('MARKETPLACE_HANDLE_VARIABLE_CHANGE', (variable, value) => ({ variable, value }))
export const createHold = createAsyncAction('CREATED_HOLD', params => api.createHold(params))
export const getCountHolds = createAsyncAction('GET_COUNT_HOLDS', () => api.getCountHolds())
export const rejectHold = createAsyncAction('REJECT_HOLD', (id) => api.rejectHold(id))
export const cancelHold = createAsyncAction('CANCEL_HOLD', (id) => api.cancelHold(id))
export const approveHold = createAsyncAction('APPROVE_HOLD', (id) => api.approveHold(id))
export const toCartHold = createAsyncAction('TO_CART_HOLD', (id) => api.toCartHold(id))
export const toggleHolds = createAction('TOGGLE_HOLDS', type => type)
export const openPopup = createAction('MARKETPLACE_OPEN_POPUP', (row = null) => row)
export const closePopup = createAction('MARKETPLACE_CLOSE_POPUP', () => null)
export const makeOffer = createAsyncAction('MARKETPLACE_MAKE_OFFER', (body) => api.makeOffer(body))
export const deleteOffer = createAsyncAction('MARKETPLACE_DELETE_OFFER', (id) => api.deleteOffer(id))
export const acceptOffer = createAsyncAction('MARKETPLACE_ACCEPT_OFFER', (id) => api.acceptOffer(id))
export const rejectOffer = createAsyncAction('MARKETPLACE_REJECT_OFFER', (id) => api.rejectOffer(id))
export const counterOffer = createAsyncAction('MARKETPLACE_COUNTER_OFFER', (id, body) => api.counterOffer(id, body))
export const addOfferToCart = createAsyncAction('MARKETPLACE_ADD_OFFER_TO_CART', (id) => api.addOfferToCart(id))
export const searchCompanies = createAsyncAction('MARKETPLACE_SEARCH_COMPANIES', (name) => api.searchCompanies(name))
export const saveSellerOption = createAction('MARKETPLACE_SAVE_SELLER_FILTER_OPTION', option => option)
