export const MARKETPLACE_OPEN_POPUP = 'MARKETPLACE_OPEN_POPUP'
export const MARKETPLACE_CLOSE_POPUP = 'MARKETPLACE_CLOSE_POPUP'

export const MARKETPLACE_FIND_PRODUCTS = 'MARKETPLACE_FIND_PRODUCTS'
export const MARKETPLACE_SEARCH_PRODUCTS = 'MARKETPLACE_SEARCH_PRODUCTS'
export const MARKETPLACE_SEARCH_PRODUCTS_PENDING = 'MARKETPLACE_SEARCH_PRODUCTS_PENDING'
export const MARKETPLACE_SEARCH_PRODUCTS_FULFILLED = 'MARKETPLACE_SEARCH_PRODUCTS_FULFILLED'

export const GET_BROADCASTED_FILTERS = 'GET_BROADCASTED_FILTERS'
export const GET_BROADCASTED_FILTERS_PENDING = 'GET_BROADCASTED_FILTERS_PENDING'
export const GET_BROADCASTED_FILTERS_FULFILLED = 'GET_BROADCASTED_FILTERS_FULFILLED'
export const GET_BROADCASTED_FILTERS_REJECTED = 'GET_BROADCASTED_FILTERS_REJECTED'

export const SAVE_BROADCASTED_FILTER = 'SAVE_BROADCASTED_FILTER'
export const SAVE_BROADCASTED_FILTER_PENDING = 'SAVE_BROADCASTED_FILTER_PENDING'
export const SAVE_BROADCASTED_FILTER_FULFILLED = 'SAVE_BROADCASTED_FILTER_FULFILLED'
export const SAVE_BROADCASTED_FILTER_REJECTED = 'SAVE_BROADCASTED_FILTER_REJECTED'

export const GET_AUTOCOMPLETE_DATA_MARKETPLACE = 'GET_AUTOCOMPLETE_DATA_MARKETPLACE'
export const GET_AUTOCOMPLETE_DATA_MARKETPLACE_PENDING = 'GET_AUTOCOMPLETE_DATA_MARKETPLACE_PENDING'
export const GET_AUTOCOMPLETE_DATA_MARKETPLACE_FULFILLED = 'GET_AUTOCOMPLETE_DATA_MARKETPLACE_FULFILLED'
export const GET_AUTOCOMPLETE_DATA_MARKETPLACE_REJECTED = 'GET_AUTOCOMPLETE_DATA_MARKETPLACE_REJECTED'

export const CLEAR_AUTOCOMPLETE_DATA = 'CLEAR_AUTOCOMPLETE_DATA'
export const MARKETPLACE_APPLY_FILTER = 'MARKETPLACE_APPLY_FILTER'
export const MARKETPLACE_HANDLE_VARIABLE_CHANGE = 'MARKETPLACE_HANDLE_VARIABLE_CHANGE'

export const MARKETPLACE_SAVE_SELLER_FILTER_OPTION = 'MARKETPLACE_SAVE_SELLER_FILTER_OPTION'

export const CREATED_HOLD = 'CREATED_HOLD'
export const CREATED_HOLD_PENDING = 'CREATED_HOLD_PENDING'
export const CREATED_HOLD_FULFILLED = 'CREATED_HOLD_FULFILLED'
export const CREATED_HOLD_REJECTED = 'CREATED_HOLD_REJECTED'

export const GET_COUNT_HOLDS = 'GET_COUNT_HOLDS'
export const GET_COUNT_HOLDS_PENDING = 'GET_COUNT_HOLDS_PENDING'
export const GET_COUNT_HOLDS_FULFILLED = 'GET_COUNT_HOLDS_FULFILLED'
export const GET_COUNT_HOLDS_REJECTED = 'GET_COUNT_HOLDS_REJECTED'

export const REJECT_HOLD = 'REJECT_HOLD'
export const REJECT_HOLD_PENDING = 'REJECT_HOLD_PENDING'
export const REJECT_HOLD_FULFILLED = 'REJECT_HOLD_FULFILLED'
export const REJECT_HOLD_REJECTED = 'REJECT_HOLD_REJECTED'

export const CANCEL_HOLD = 'CANCEL_HOLD'
export const CANCEL_HOLD_PENDING = 'CANCEL_HOLD_PENDING'
export const CANCEL_HOLD_FULFILLED = 'CANCEL_HOLD_FULFILLED'
export const CANCEL_HOLD_REJECTED = 'CANCEL_HOLD_REJECTED'

export const APPROVE_HOLD = 'APPROVE_HOLD'
export const APPROVE_HOLD_PENDING = 'APPROVE_HOLD_PENDING'
export const APPROVE_HOLD_FULFILLED = 'APPROVE_HOLD_FULFILLED'
export const APPROVE_HOLD_REJECTED = 'APPROVE_HOLD_REJECTED'

export const TO_CART_HOLD = 'TO_CART_HOLD'
export const TO_CART_HOLD_PENDING = 'TO_CART_HOLD_PENDING'
export const TO_CART_HOLD_FULFILLED = 'TO_CART_HOLD_FULFILLED'
export const TO_CART_HOLD_REJECTED = 'TO_CART_HOLD_REJECTED'

export const HOLD_APPLY_FILTER = 'HOLD_APPLY_FILTER'

export const TOGGLE_HOLDS = 'TOGGLE_HOLDS'

export const MARKETPLACE_MAKE_OFFER = 'MARKETPLACE_MAKE_OFFER'
export const MARKETPLACE_MAKE_OFFER_PENDING = 'MARKETPLACE_MAKE_OFFER_PENDING'
export const MARKETPLACE_MAKE_OFFER_FULFILLED = 'MARKETPLACE_MAKE_OFFER_FULFILLED'
export const MARKETPLACE_MAKE_OFFER_REJECTED = 'MARKETPLACE_MAKE_OFFER_REJECTED'

export const MARKETPLACE_DELETE_OFFER = 'MARKETPLACE_DELETE_OFFER'
export const MARKETPLACE_DELETE_OFFER_PENDING = 'MARKETPLACE_DELETE_OFFER_PENDING'
export const MARKETPLACE_DELETE_OFFER_FULFILLED = 'MARKETPLACE_DELETE_OFFER_FULFILLED'
export const MARKETPLACE_DELETE_OFFER_REJECTED = 'MARKETPLACE_DELETE_OFFER_REJECTED'

export const MARKETPLACE_ACCEPT_OFFER = 'MARKETPLACE_ACCEPT_OFFER'
export const MARKETPLACE_ACCEPT_OFFER_PENDING = 'MARKETPLACE_ACCEPT_OFFER_PENDING'
export const MARKETPLACE_ACCEPT_OFFER_FULFILLED = 'MARKETPLACE_ACCEPT_OFFER_FULFILLED'
export const MARKETPLACE_ACCEPT_OFFER_REJECTED = 'MARKETPLACE_ACCEPT_OFFER_REJECTED'

export const MARKETPLACE_REJECT_OFFER = 'MARKETPLACE_REJECT_OFFER'
export const MARKETPLACE_REJECT_OFFER_PENDING = 'MARKETPLACE_REJECT_OFFER_PENDING'
export const MARKETPLACE_REJECT_OFFER_FULFILLED = 'MARKETPLACE_REJECT_OFFER_FULFILLED'
export const MARKETPLACE_REJECT_OFFER_REJECTED = 'MARKETPLACE_REJECT_OFFER_REJECTED'

export const MARKETPLACE_COUNTER_OFFER = 'MARKETPLACE_COUNTER_OFFER'
export const MARKETPLACE_COUNTER_OFFER_PENDING = 'MARKETPLACE_COUNTER_OFFER_PENDING'
export const MARKETPLACE_COUNTER_OFFER_FULFILLED = 'MARKETPLACE_COUNTER_OFFER_FULFILLED'
export const MARKETPLACE_COUNTER_OFFER_REJECTED = 'MARKETPLACE_COUNTER_OFFER_REJECTED'

export const MARKETPLACE_ADD_OFFER_TO_CART = 'MARKETPLACE_ADD_OFFER_TO_CART'
export const MARKETPLACE_ADD_OFFER_TO_CART_PENDING = 'MARKETPLACE_ADD_OFFER_TO_CART_PENDING'
export const MARKETPLACE_ADD_OFFER_TO_CART_FULFILLED = 'MARKETPLACE_ADD_OFFER_TO_CART_FULFILLED'
export const MARKETPLACE_ADD_OFFER_TO_CART_REJECTED = 'MARKETPLACE_ADD_OFFER_TO_CART_REJECTED'

export const MARKETPLACE_SEARCH_COMPANIES = 'MARKETPLACE_SEARCH_COMPANIES'
export const MARKETPLACE_SEARCH_COMPANIES_PENDING = 'MARKETPLACE_SEARCH_COMPANIES_PENDING'
export const MARKETPLACE_SEARCH_COMPANIES_FULFILLED = 'MARKETPLACE_SEARCH_COMPANIES_FULFILLED'
export const MARKETPLACE_SEARCH_COMPANIES_REJECTED = 'MARKETPLACE_SEARCH_COMPANIES_REJECTED'