export const CREATED_HOLD = 'CREATED_HOLD'
export const CREATED_HOLD_PENDING = 'CREATED_HOLD_PENDING'
export const CREATED_HOLD_FULFILLED = 'CREATED_HOLD_FULFILLED'
export const CREATED_HOLD_REJECTED = 'CREATED_HOLD_REJECTED'

export const GET_MY_HOLDS = 'GET_MY_HOLDS'
export const GET_MY_HOLDS_PENDING = 'GET_MY_HOLDS_PENDING'
export const GET_MY_HOLDS_FULFILLED = 'GET_MY_HOLDS_FULFILLED'
export const GET_MY_HOLDS_REJECTED = 'GET_MY_HOLDS_REJECTED'

export const GET_FOREIGN_HOLDS = 'GET_FOREIGN_HOLDS'
export const GET_FOREIGN_HOLDS_PENDING = 'GET_FOREIGN_HOLDS_PENDING'
export const GET_FOREIGN_HOLDS_FULFILLED = 'GET_FOREIGN_HOLDS_FULFILLED'
export const GET_FOREIGN_HOLDS_REJECTED = 'GET_FOREIGN_HOLDS_REJECTED'

export const REJECT_HOLD = 'REJECT_HOLD'
export const REJECT_HOLD_PENDING = 'REJECT_HOLD_PENDING'
export const REJECT_HOLD_FULFILLED = 'REJECT_HOLD_FULFILLED'
export const REJECT_HOLD_REJECTED = 'REJECT_HOLD_REJECTED'

export const CANCEL_HOLD = 'CANCEL_HOLD'
export const CANCEL_HOLD_PENDING = 'CANCEL_HOLD_PENDING'
export const CANCEL_HOLD_FULFILLED = 'CANCEL_HOLD_FULFILLED'
export const CANCEL_HOLD_REJECTED = 'CANCEL_HOLD_REJECTED'

export const APPROVE_HOLD = 'APPROVE_HOLD'
export const APPROVE_HOLD_PENDING = 'APPROVE_HOLD_PENDING'
export const APPROVE_HOLD_FULFILLED = 'APPROVE_HOLD_FULFILLED'
export const APPROVE_HOLD_REJECTED = 'APPROVE_HOLD_REJECTED'

export const TO_CART_HOLD = 'TO_CART_HOLD'
export const TO_CART_HOLD_PENDING = 'TO_CART_HOLD_PENDING'
export const TO_CART_HOLD_FULFILLED = 'TO_CART_HOLD_FULFILLED'
export const TO_CART_HOLD_REJECTED = 'TO_CART_HOLD_REJECTED'
