export const SEARCH_TAGS = 'SEARCH_TAGS'
export const SEARCH_TAGS_PENDING = 'SEARCH_TAGS_PENDING'
export const SEARCH_TAGS_FULFILLED = 'SEARCH_TAGS_FULFILLED'
export const SEARCH_TAGS_REJECTED = 'SEARCH_TAGS_REJECTED'

export const SEARCH_PRODUCT_OFFERS_INVENTORY = 'SEARCH_PRODUCT_OFFERS_INVENTORY'
export const SEARCH_PRODUCT_OFFERS_INVENTORY_PENDING = 'SEARCH_PRODUCT_OFFERS_INVENTORY_PENDING'
export const SEARCH_PRODUCT_OFFERS_INVENTORY_FULFILLED = 'SEARCH_PRODUCT_OFFERS_INVENTORY_FULFILLED'
export const SEARCH_PRODUCT_OFFERS_INVENTORY_REJECTED = 'SEARCH_PRODUCT_OFFERS_INVENTORY_REJECTED'

export const SEARCH_CLEAR_PRODUCT_OFFERS = 'SEARCH_CLEAR_PRODUCT_OFFERS'
