export const SEARCH_TAGS = 'SEARCH_TAGS'
export const SEARCH_TAGS_PENDING = 'SEARCH_TAGS_PENDING'
export const SEARCH_TAGS_FULFILLED = 'SEARCH_TAGS_FULFILLED'
export const SEARCH_TAGS_REJECTED = 'SEARCH_TAGS_REJECTED'
