export const ADMIN_OPEN_EDIT_POPUP = 'ADMIN_OPEN_EDIT_POPUP'
export const ADMIN_CLOSE_EDIT_POPUP = 'ADMIN_CLOSE_EDIT_POPUP'
export const ADMIN_OPEN_ADD_POPUP = 'ADMIN_OPEN_ADD_POPUP'
export const ADMIN_CLOSE_ADD_POPUP = 'ADMIN_CLOSE_ADD_POPUP'
export const ADMIN_DELETE_ITEM = 'ADMIN_DELETE_ITEM'



export const ADMIN_HANDLE_ACTIVE_TAB = 'ADMIN_HANDLE_ACTIVE_TAB'
export const ADMIN_HANDLE_FILTERS_VALUE = 'ADMIN_HANDLE_FILTERS_VALUE'
