export const ADMIN_OPEN_EDIT_POPUP = 'ADMIN_OPEN_EDIT_POPUP'
export const ADMIN_CLOSE_EDIT_POPUP = 'ADMIN_CLOSE_EDIT_POPUP'
export const ADMIN_OPEN_ADD_POPUP = 'ADMIN_OPEN_ADD_POPUP'
export const ADMIN_CLOSE_ADD_POPUP = 'ADMIN_CLOSE_ADD_POPUP'
export const ADMIN_CLOSE_CONFIRM_POPUP = 'ADMIN_CLOSE_CONFIRM_POPUP'
export const ADMIN_DELETE_ITEM = 'ADMIN_DELETE_ITEM'
export const ADMIN_HANDLE_ACTIVE_TAB = 'ADMIN_HANDLE_ACTIVE_TAB'
export const ADMIN_HANDLE_FILTERS_VALUE = 'ADMIN_HANDLE_FILTERS_VALUE'
export const ADMIN_GET_CAS_PRODUCT_BY_FILTER = 'ADMIN_GET_CAS_PRODUCT_BY_FILTER'
export const ADMIN_GET_CAS_PRODUCT_BY_FILTER_FULFILLED = 'ADMIN_GET_CAS_PRODUCT_BY_FILTER_FULFILLED'
export const ADMIN_GET_CAS_PRODUCT_BY_STRING = 'ADMIN_GET_CAS_PRODUCT_BY_STRING'
export const ADMIN_GET_CAS_PRODUCT_BY_STRING_FULFILLED = 'ADMIN_GET_CAS_PRODUCT_BY_STRING_FULFILLED'

export const ADMIN_GET_HAZARD_CLASSES = 'ADMIN_GET_HAZARD_CLASSES'
export const ADMIN_GET_HAZARD_CLASSES_FULFILLED = 'ADMIN_GET_HAZARD_CLASSES_FULFILLED'
export const ADMIN_GET_PACKAGING_GROUPS = 'ADMIN_GET_PACKAGING_GROUPS'
export const ADMIN_GET_PACKAGING_GROUPS_FULFILLED = 'ADMIN_GET_PACKAGING_GROUPS_FULFILLED'

export const ADMIN_GET_COMPANIES = 'ADMIN_GET_COMPANIES'
export const ADMIN_GET_COMPANIES_PENDING = 'ADMIN_GET_COMPANIES_PENDING'
export const ADMIN_GET_COMPANIES_FULFILLED = 'ADMIN_GET_COMPANIES_FULFILLED'
export const ADMIN_GET_COMPANIES_REJECTED = 'ADMIN_GET_COMPANIES_REJECTED'



