export const ADMIN_OPEN_EDIT_POPUP = 'ADMIN_OPEN_EDIT_POPUP'
export const ADMIN_CLOSE_EDIT_POPUP = 'ADMIN_CLOSE_EDIT_POPUP'
export const ADMIN_OPEN_ADD_POPUP = 'ADMIN_OPEN_ADD_POPUP'
export const ADMIN_CLOSE_ADD_POPUP = 'ADMIN_CLOSE_ADD_POPUP'


export const ADMIN_HANDLE_ACTIVE_TAB = 'ADMIN_HANDLE_ACTIVE_TAB'
export const ADMIN_HANDLE_FILTERS_VALUE = 'ADMIN_HANDLE_FILTERS_VALUE'





export const ADMIN_GET_UNITS_OF_MEASURE_DATA = 'ADMIN_GET_UNITS_OF_MEASURE_DATA'
export const ADMIN_GET_UNITS_OF_MEASURE_DATA_SUCCESS = 'ADMIN_GET_UNITS_OF_MEASURE_DATA_SUCCESS'